package de.ipk.ag_ba.image.operations.blocks.properties;

public enum PropertyNames {
	TRANSLATION_FLUO_X, TRANSLATION_FLUO_Y, TRANSLATION_NIR_X, TRANSLATION_NIR_Y, ROTATION_FLUO,
	ROTATION_NIR, SCALING_FLUO_X, SCALING_FLUO_Y, SCALING_NIR_X, SCALING_NIR_Y, HEIGHT_FLUO_IMAGE,
	HEIGHT_FLUO_MASK, HEIGHT_NIR_IMAGE, HEIGHT_NIR_MASK, HEIGHT_VIS_IMAGE, HEIGHT_VIS_MASK, WIDTH_FLUO_IMAGE,
	WIDTH_FLUO_MASK, WIDTH_NIR_IMAGE, WIDTH_NIR_MASK, WIDTH_VIS_IMAGE, WIDTH_VIS_MASK, END_HEIGHT_FLUO_IMAGE,
	END_WIDTH_FLUO_IMAGE, END_HEIGHT_FLUO_MASK, END_WIDTH_FLUO_MASK, END_HEIGHT_NIR_IMAGE, END_WIDTH_NIR_IMAGE,
	END_HEIGHT_NIR_MASK, END_WIDTH_NIR_MASK, END_HEIGHT_VIS_IMAGE, END_WIDTH_VIS_IMAGE, END_HEIGHT_VIS_MASK, END_WIDTH_VIS_MASK,

	VIS_MARKER_POS_LEFT_1, VIS_MARKER_POS_LEFT_2, VIS_MARKER_POS_LEFT_3,
	VIS_MARKER_POS_RIGHT_1, VIS_MARKER_POS_RIGHT_2, VIS_MARKER_POS_RIGHT_3,

	RESULT_MAXIMUM_SEARCH;
	
	public boolean storeAsResult() {
		switch (this) {
			case VIS_MARKER_POS_LEFT_1:
			case VIS_MARKER_POS_LEFT_2:
			case VIS_MARKER_POS_LEFT_3:
			case VIS_MARKER_POS_RIGHT_1:
			case VIS_MARKER_POS_RIGHT_2:
			case VIS_MARKER_POS_RIGHT_3:
				return true;
				
			default:
				return false;
		}
	}
	
}
