/*
 * ----------------------------------------------------------------------------
 * This file was automatically generated by SWIG (http://www.swig.org).
 * Version 1.3.31
 * Do not make changes to this file unless you know what you are doing--modify
 * the SWIG interface file instead.
 * -----------------------------------------------------------------------------
 */

package colajava;

public class CompoundConstraintsVector {
	private long swigCPtr;
	protected boolean swigCMemOwn;
	
	protected CompoundConstraintsVector(long cPtr, boolean cMemoryOwn) {
		swigCMemOwn = cMemoryOwn;
		swigCPtr = cPtr;
	}
	
	protected static long getCPtr(CompoundConstraintsVector obj) {
		return (obj == null) ? 0 : obj.swigCPtr;
	}
	
	@Override
	protected void finalize() {
		delete();
	}
	
	public synchronized void delete() {
		if (swigCPtr != 0 && swigCMemOwn) {
			swigCMemOwn = false;
			colaJNI.delete_CompoundConstraintsVector(swigCPtr);
		}
		swigCPtr = 0;
	}
	
	public CompoundConstraintsVector() {
		this(colaJNI.new_CompoundConstraintsVector__SWIG_0(), true);
	}
	
	public CompoundConstraintsVector(long n) {
		this(colaJNI.new_CompoundConstraintsVector__SWIG_1(n), true);
	}
	
	public long size() {
		return colaJNI.CompoundConstraintsVector_size(swigCPtr, this);
	}
	
	public long capacity() {
		return colaJNI.CompoundConstraintsVector_capacity(swigCPtr, this);
	}
	
	public void reserve(long n) {
		colaJNI.CompoundConstraintsVector_reserve(swigCPtr, this, n);
	}
	
	public boolean isEmpty() {
		return colaJNI.CompoundConstraintsVector_isEmpty(swigCPtr, this);
	}
	
	public void clear() {
		colaJNI.CompoundConstraintsVector_clear(swigCPtr, this);
	}
	
	public void add(CompoundConstraint x) {
		colaJNI.CompoundConstraintsVector_add(swigCPtr, this, CompoundConstraint.getCPtr(x));
	}
	
	public CompoundConstraint get(int i) {
		long cPtr = colaJNI.CompoundConstraintsVector_get(swigCPtr, this, i);
		return (cPtr == 0) ? null : new CompoundConstraint(cPtr, false);
	}
	
	public void set(int i, CompoundConstraint x) {
		colaJNI.CompoundConstraintsVector_set(swigCPtr, this, i, CompoundConstraint.getCPtr(x));
	}
	
}
