/*
 * ----------------------------------------------------------------------------
 * This file was automatically generated by SWIG (http://www.swig.org).
 * Version 1.3.31
 * Do not make changes to this file unless you know what you are doing--modify
 * the SWIG interface file instead.
 * -----------------------------------------------------------------------------
 */

package colajava;

public class MultiSeparationConstraint extends CompoundConstraint {
	private long swigCPtr;
	
	protected MultiSeparationConstraint(long cPtr, boolean cMemoryOwn) {
		super(colaJNI.SWIGMultiSeparationConstraintUpcast(cPtr), cMemoryOwn);
		swigCPtr = cPtr;
	}
	
	protected static long getCPtr(MultiSeparationConstraint obj) {
		return (obj == null) ? 0 : obj.swigCPtr;
	}
	
	@Override
	protected void finalize() {
		delete();
	}
	
	@Override
	public synchronized void delete() {
		if (swigCPtr != 0 && swigCMemOwn) {
			swigCMemOwn = false;
			colaJNI.delete_MultiSeparationConstraint(swigCPtr);
		}
		swigCPtr = 0;
		super.delete();
	}
	
	public MultiSeparationConstraint(double minSep, boolean equality) {
		this(colaJNI.new_MultiSeparationConstraint__SWIG_0(minSep, equality), true);
	}
	
	public MultiSeparationConstraint(double minSep) {
		this(colaJNI.new_MultiSeparationConstraint__SWIG_1(minSep), true);
	}
	
	public MultiSeparationConstraint() {
		this(colaJNI.new_MultiSeparationConstraint__SWIG_2(), true);
	}
	
	@Override
	public void generateVariables(SWIGTYPE_p_std__vectorTvpsc__Variable_p_t vars) {
		colaJNI.MultiSeparationConstraint_generateVariables(swigCPtr, this, SWIGTYPE_p_std__vectorTvpsc__Variable_p_t.getCPtr(vars));
	}
	
	@Override
	public void generateSeparationConstraints(SWIGTYPE_p_std__vectorTvpsc__Variable_p_t vs, SWIGTYPE_p_std__vectorTvpsc__Constraint_p_t gcs) {
		colaJNI.MultiSeparationConstraint_generateSeparationConstraints(swigCPtr, this, SWIGTYPE_p_std__vectorTvpsc__Variable_p_t.getCPtr(vs),
							SWIGTYPE_p_std__vectorTvpsc__Constraint_p_t.getCPtr(gcs));
	}
	
	public void setSeparation(double sep) {
		colaJNI.MultiSeparationConstraint_setSeparation(swigCPtr, this, sep);
	}
	
	public void setCs(SWIGTYPE_p_std__vectorTvpsc__Constraint_p_t value) {
		colaJNI.MultiSeparationConstraint_cs_set(swigCPtr, this, SWIGTYPE_p_std__vectorTvpsc__Constraint_p_t.getCPtr(value));
	}
	
	public SWIGTYPE_p_std__vectorTvpsc__Constraint_p_t getCs() {
		long cPtr = colaJNI.MultiSeparationConstraint_cs_get(swigCPtr, this);
		return (cPtr == 0) ? null : new SWIGTYPE_p_std__vectorTvpsc__Constraint_p_t(cPtr, false);
	}
	
	public void setAcs(AlignmentConstraintPairList value) {
		colaJNI.MultiSeparationConstraint_acs_set(swigCPtr, this, AlignmentConstraintPairList.getCPtr(value), value);
	}
	
	public AlignmentConstraintPairList getAcs() {
		long cPtr = colaJNI.MultiSeparationConstraint_acs_get(swigCPtr, this);
		return (cPtr == 0) ? null : new AlignmentConstraintPairList(cPtr, false);
	}
	
	public void setIndicator(SWIGTYPE_p_void value) {
		colaJNI.MultiSeparationConstraint_indicator_set(swigCPtr, this, SWIGTYPE_p_void.getCPtr(value));
	}
	
	public SWIGTYPE_p_void getIndicator() {
		long cPtr = colaJNI.MultiSeparationConstraint_indicator_get(swigCPtr, this);
		return (cPtr == 0) ? null : new SWIGTYPE_p_void(cPtr, false);
	}
	
	public void setSep(double value) {
		colaJNI.MultiSeparationConstraint_sep_set(swigCPtr, this, value);
	}
	
	public double getSep() {
		return colaJNI.MultiSeparationConstraint_sep_get(swigCPtr, this);
	}
	
	public void setEquality(boolean value) {
		colaJNI.MultiSeparationConstraint_equality_set(swigCPtr, this, value);
	}
	
	public boolean getEquality() {
		return colaJNI.MultiSeparationConstraint_equality_get(swigCPtr, this);
	}
	
}
