/*
 * ----------------------------------------------------------------------------
 * This file was automatically generated by SWIG (http://www.swig.org).
 * Version 1.3.31
 * Do not make changes to this file unless you know what you are doing--modify
 * the SWIG interface file instead.
 * -----------------------------------------------------------------------------
 */

package colajava;

public class Polygon extends PolygonInterface {
	private long swigCPtr;
	
	protected Polygon(long cPtr, boolean cMemoryOwn) {
		super(colaJNI.SWIGPolygonUpcast(cPtr), cMemoryOwn);
		swigCPtr = cPtr;
	}
	
	protected static long getCPtr(Polygon obj) {
		return (obj == null) ? 0 : obj.swigCPtr;
	}
	
	@Override
	protected void finalize() {
		delete();
	}
	
	@Override
	public synchronized void delete() {
		if (swigCPtr != 0 && swigCMemOwn) {
			swigCMemOwn = false;
			colaJNI.delete_Polygon(swigCPtr);
		}
		swigCPtr = 0;
		super.delete();
	}
	
	public Polygon() {
		this(colaJNI.new_Polygon__SWIG_0(), true);
	}
	
	public Polygon(int pn) {
		this(colaJNI.new_Polygon__SWIG_1(pn), true);
	}
	
	public Polygon(PolygonInterface poly) {
		this(colaJNI.new_Polygon__SWIG_2(PolygonInterface.getCPtr(poly), poly), true);
	}
	
	@Override
	public void clear() {
		colaJNI.Polygon_clear(swigCPtr, this);
	}
	
	@Override
	public boolean empty() {
		return colaJNI.Polygon_empty(swigCPtr, this);
	}
	
	@Override
	public int size() {
		return colaJNI.Polygon_size(swigCPtr, this);
	}
	
	@Override
	public int id() {
		return colaJNI.Polygon_id(swigCPtr, this);
	}
	
	@Override
	public Point at(int index) {
		return new Point(colaJNI.Polygon_at(swigCPtr, this, index), false);
	}
	
	public Polygon curvedPolyline(double curve_amount) {
		return new Polygon(colaJNI.Polygon_curvedPolyline(swigCPtr, this, curve_amount), true);
	}
	
	public void set_id(int value) {
		colaJNI.Polygon__id_set(swigCPtr, this, value);
	}
	
	public int get_id() {
		return colaJNI.Polygon__id_get(swigCPtr, this);
	}
	
	public void setPs(SWIGTYPE_p_std__vectorTAvoid__Point_t value) {
		colaJNI.Polygon_ps_set(swigCPtr, this, SWIGTYPE_p_std__vectorTAvoid__Point_t.getCPtr(value));
	}
	
	public SWIGTYPE_p_std__vectorTAvoid__Point_t getPs() {
		long cPtr = colaJNI.Polygon_ps_get(swigCPtr, this);
		return (cPtr == 0) ? null : new SWIGTYPE_p_std__vectorTAvoid__Point_t(cPtr, false);
	}
	
	public void setTs(SWIGTYPE_p_std__vectorTchar_t value) {
		colaJNI.Polygon_ts_set(swigCPtr, this, SWIGTYPE_p_std__vectorTchar_t.getCPtr(value));
	}
	
	public SWIGTYPE_p_std__vectorTchar_t getTs() {
		long cPtr = colaJNI.Polygon_ts_get(swigCPtr, this);
		return (cPtr == 0) ? null : new SWIGTYPE_p_std__vectorTchar_t(cPtr, false);
	}
	
}
