/*
 * ----------------------------------------------------------------------------
 * This file was automatically generated by SWIG (http://www.swig.org).
 * Version 1.3.31
 * Do not make changes to this file unless you know what you are doing--modify
 * the SWIG interface file instead.
 * -----------------------------------------------------------------------------
 */

package colajava;

public class OffsetList {
	private long swigCPtr;
	protected boolean swigCMemOwn;
	
	protected OffsetList(long cPtr, boolean cMemoryOwn) {
		swigCMemOwn = cMemoryOwn;
		swigCPtr = cPtr;
	}
	
	protected static long getCPtr(OffsetList obj) {
		return (obj == null) ? 0 : obj.swigCPtr;
	}
	
	@Override
	protected void finalize() {
		delete();
	}
	
	public synchronized void delete() {
		if (swigCPtr != 0 && swigCMemOwn) {
			swigCMemOwn = false;
			colaJNI.delete_OffsetList(swigCPtr);
		}
		swigCPtr = 0;
	}
	
	public OffsetList() {
		this(colaJNI.new_OffsetList__SWIG_0(), true);
	}
	
	public OffsetList(long n) {
		this(colaJNI.new_OffsetList__SWIG_1(n), true);
	}
	
	public long size() {
		return colaJNI.OffsetList_size(swigCPtr, this);
	}
	
	public long capacity() {
		return colaJNI.OffsetList_capacity(swigCPtr, this);
	}
	
	public void reserve(long n) {
		colaJNI.OffsetList_reserve(swigCPtr, this, n);
	}
	
	public boolean isEmpty() {
		return colaJNI.OffsetList_isEmpty(swigCPtr, this);
	}
	
	public void clear() {
		colaJNI.OffsetList_clear(swigCPtr, this);
	}
	
	public void add(OffsetPair x) {
		colaJNI.OffsetList_add(swigCPtr, this, OffsetPair.getCPtr(x), x);
	}
	
	public OffsetPair get(int i) {
		return new OffsetPair(colaJNI.OffsetList_get(swigCPtr, this, i), false);
	}
	
	public void set(int i, OffsetPair x) {
		colaJNI.OffsetList_set(swigCPtr, this, i, OffsetPair.getCPtr(x), x);
	}
	
}
