# TODO: Add comment
# 
# Author: Entzian
###############################################################################

nBoxOptions= NULL

nBox.plot.list <- list(
		"Weight A (g)" = "weight before watering (g)", 
		"Weight B (g)" = "weight after watering (g)",
		"Water (sum of day)" = "water weight (g)",
		#"Water (weight-diff)" = "water weight (g)", 
		"side.height.norm (mm)" = "height (zoom corrected) (mm)", 
		"side.width.norm (mm)" = "width (zoom corrected) (mm)", 
		"side.area.norm (mm^2)" = "side area (zoom corrected) (mm^2)", 
		"top.area.norm (mm^2)" = "top area (zoom corrected) (mm^2)", 											
		"side.fluo.intensity.chlorophyl.average (relative)" = "chlorophyll intensity (relative intensity/pixel)", 
		"side.fluo.intensity.phenol.average (relative)" = "fluorescence intensity (relative intensity/pixel)", 
		"side.nir.intensity.average (relative)" = "side nir intensity (relative intensity/pixel)",
		"top.nir.intensity.average (relative / pix)" = "top nir intensity (relative intensity/pixel)",												
		"side.leaf.count.median (leafs)" = "number of leafs", 
		"side.bloom.count (tassel)" = "number of tassel florets", 
		"side.leaf.length.sum.norm.max (mm)" = "length of leafs plus stem (mm)", 
		"volume.iap (px^3)" = "digital biomass (visible light images, IAP formula) (px^3)", 
		"volume.lt (px^3)" = "digital biomass (visible light, LemnaTec 0,90 formula) (px^3)", 
		"volume.iap.wue" = "volume based water use efficiency",
		"side.area.avg.wue" = "digital side area based water use efficiency",
		"side.nir.wetness.plant_weight_drought_loss" = "weighted loss through drought stress (side)", 
		"top.nir.wetness.plant_weight_drought_loss" = "weighted loss through drought stress (top)", 	
		"side.nir.wetness.average (percent)" = "Average wetness of side image", 
		"top.nir.wetness.average (percent)" = "Average wetness of top image", 
		#"side.area.relative" = "growth in %/day", 
		"side.height.norm.relative" = "plant height growth rate (%/day)", 
		"side.width.norm.relative" = "plant width growth rate (%/day)", 
		"top.area.relative" = "top area growth rate (%/day)", 
		"side.area.relative" = "side area growth rate (%/day)", 
		"volume.iap.relative" = "volume growth (visible light images, IAP based formula) (%/day)", 
		"side.height (px)" = "height (px)", 
		"side.width (px)" = "width (px)", 
		"side.area (px)" = "side area (px)", 
		"top.area (px)" = "top area (px)",
		"side.hull.area (px)" = "side area of convex hull (px)",
		"side.hull.area.norm (mm^2)" = "side area of convex hull (zoom corrected) (mm^2)",
		"side.hull.pc1" = "side maximum extension (px)",
		"side.hull.pc1.norm" = "side maximum extension (zoom corrected) (mm)",
		"side.hull.pc2" = "opposite direction of the side maximum extension (px)",
		"side.hull.pc2.norm" = "opposite direction of the side maximum extension (zoom corrected) (mm)",
		"side.hull.fillgrade (percent)" = "fillgrade of side convex hull (%)",		
		"top.hull.area (px)" = "top area of convex hull (px)",	
		"top.hull.area.norm (mm^2)" = "top area of convex hull (zoom corrected) (mm^2)",
		"top.hull.pc1" = "top maximum extension (px)",
		"top.hull.pc1.norm" = "top maximum extension (zoom corrected) (mm)",
		"top.hull.pc2" = "opposite direction of the top maximum extension (px)",
		"top.hull.pc2.norm" = "opposite direction of the top maximum extension (zoom corrected) (mm)",
		"top.hull.fillgrade (percent)" = "fillgrade of top convex hull (%)",
		"side.vis.hue.average" = "side visible hue average value",
		"top.vis.hue.average" = "top visible hue average value",
		"mark1.y (percent)" = "blue marker position from top (%)",
		#"mark2.y (percent)" = "blue marker position from middle (%)",
		"mark3.y (percent)" = "blue marker position from bottom  (%)",
		"top.ir.intensity.average" = "top ir intensity",
		"side.ir.intensity.average" = "side ir intensity",
		"side.nir.skeleton.intensity.average (relative)" = "side skeleton nir intensity (relative intensity/pixel)",
		"top.nir.skeleton.intensity.average" = "top skeleton nir intensity (relative intensity/pixel)",	
		"side.compactness.16 (relative)" = "side compactness (1-16)",
		"top.compactness.16 (relative)" = "top compactness (1-16)",
		"side.hull.circularity (relative)" = "side circularity",
		"top.hull.circularity (relative)" = "top circularity",
		"side.compactness.01 (relative)" = "side compactness (0-1)",		
		"top.compactness.01 (relative)" = "top compactness (0-1)",
		"side.fluo.intensity.average (relative)" = "side fluo intensity (relative intensity/pixel)",
		"top.fluo.intensity.average (relative / pix)" = "top fluo intensity (relative intensity/pixel)",
		"side.hull.circumcircle.d (px)" = "side circumcircle diameter (px)",
		"top.hull.circumcircle.d (px)" = "top circumcircle diameter (px)",
		"side.vis.hsv.h.histogram.bin.01.0_12" = "side rgb h - bin1",
		"side.vis.hsv.h.histogram.bin.02.12_25" = "side rgb h - bin2",
		"side.vis.hsv.h.histogram.bin.03.25_38" = "side rgb h - bin3",
		"side.vis.hsv.h.histogram.bin.04.38_51" = "side rgb h - bin4",
		"side.vis.hsv.h.histogram.bin.05.51_63" = "side rgb h - bin5",
		"side.vis.hsv.h.histogram.bin.06.63_76" = "side rgb h - bin6",
		"top.vis.hsv.h.histogram.bin.01.0_12" = "top rgb h - bin1",
		"top.vis.hsv.h.histogram.bin.02.12_25" = "top rgb h - bin2",
		"top.vis.hsv.h.histogram.bin.03.25_38" = "top rgb h - bin3",
		"top.vis.hsv.h.histogram.bin.04.38_51" = "top rgb h - bin4",
		"top.vis.hsv.h.histogram.bin.05.51_63" = "top rgb h - bin5",
		"top.vis.hsv.h.histogram.bin.06.63_76" = "top rgb h - bin6",
		"side.vis.hsv.h.kurtosis" = "side rgb h - kurtosis",
		"side.vis.hsv.h.skewness" = "side rgb h - skewness",
		"side.vis.hsv.h.stddev" = "side rgb h - stddev",
		"side.vis.hsv.h.average" = "side rgb h - average",
		"top.vis.hsv.h.kurtosis" = "top rgb h - kurtosis",
		"top.vis.hsv.h.skewness" = "top rgb h - skewness",
		"top.vis.hsv.h.stddev" = "top rgb h - stddev",
		"top.vis.hsv.h.average" = "top rgb h - average",
		
		"side.vis.hsv.h.normalized.histogram.bin.01.0_12" = "side rgb h - bin1",
		"side.vis.hsv.h.normalized.histogram.bin.02.12_25" = "side rgb h - bin2",
		"side.vis.hsv.h.normalized.histogram.bin.03.25_38" = "side rgb h - bin3",
		"side.vis.hsv.h.normalized.histogram.bin.04.38_51" = "side rgb h - bin4",
		"side.vis.hsv.h.normalized.histogram.bin.05.51_63" = "side rgb h - bin5",
		"side.vis.hsv.h.normalized.histogram.bin.06.63_76" = "side rgb h - bin6",
		"top.vis.hsv.h.normalized.histogram.bin.01.0_12" = "top rgb h - bin1",
		"top.vis.hsv.h.normalized.histogram.bin.02.12_25" = "top rgb h - bin2",
		"top.vis.hsv.h.normalized.histogram.bin.03.25_38" = "top rgb h - bin3",
		"top.vis.hsv.h.normalized.histogram.bin.04.38_51" = "top rgb h - bin4",
		"top.vis.hsv.h.normalized.histogram.bin.05.51_63" = "top rgb h - bin5",
		"top.vis.hsv.h.normalized.histogram.bin.06.63_76" = "top rgb h - bin6",
		"side.vis.hsv.h.normalized.kurtosis" = "side rgb h - kurtosis",
		"side.vis.hsv.h.normalized.skewness" = "side rgb h - skewness",
		"side.vis.hsv.h.normalized.stddev" = "side rgb h - stddev",
		"side.vis.hsv.h.normalized.average" = "side rgb h - average",
		"top.vis.hsv.h.normalized.kurtosis" = "top rgb h - kurtosis",
		"top.vis.hsv.h.normalized.skewness" = "top rgb h - skewness",
		"top.vis.hsv.h.normalized.stddev" = "top rgb h - stddev",
		"top.vis.hsv.h.normalized.average" = "top rgb h - average",
			
		"side.vis.hsv.s.histogram.bin.01.0_12" = "side rgb s - bin1",
		"side.vis.hsv.s.histogram.bin.02.12_25" = "side rgb s - bin2",
		"side.vis.hsv.s.histogram.bin.03.25_38" = "side rgb s - bin3",
		"side.vis.hsv.s.histogram.bin.04.38_51" = "side rgb s - bin4",
		"side.vis.hsv.s.histogram.bin.05.51_63" = "side rgb s - bin5",
		"side.vis.hsv.s.histogram.bin.06.63_76" = "side rgb s - bin6",
		"top.vis.hsv.s.histogram.bin.01.0_12" = "top rgb s - bin1",
		"top.vis.hsv.s.histogram.bin.02.12_25" = "top rgb s - bin2",
		"top.vis.hsv.s.histogram.bin.03.25_38" = "top rgb s - bin3",
		"top.vis.hsv.s.histogram.bin.04.38_51" = "top rgb s - bin4",
		"top.vis.hsv.s.histogram.bin.05.51_63" = "top rgb s - bin5",
		"top.vis.hsv.s.histogram.bin.06.63_76" = "top rgb s - bin6",
		"side.vis.hsv.s.kurtosis" = "side rgb s - kurtosis",
		"side.vis.hsv.s.skewness" = "side rgb s - skewness",
		"side.vis.hsv.s.stddev" = "side rgb s - stddev",
		"side.vis.hsv.s.average" = "side rgb s - average",
		"top.vis.hsv.s.kurtosis" = "top rgb s - kurtosis",
		"top.vis.hsv.s.skewness" = "top rgb s - skewness",
		"top.vis.hsv.s.stddev" = "top rgb s - stddev",
		"top.vis.hsv.s.average" = "top rgb s - average",
		
		"side.vis.hsv.s.normalized.histogram.bin.01.0_12" = "side rgb s - bin1",
		"side.vis.hsv.s.normalized.histogram.bin.02.12_25" = "side rgb s - bin2",
		"side.vis.hsv.s.normalized.histogram.bin.03.25_38" = "side rgb s - bin3",
		"side.vis.hsv.s.normalized.histogram.bin.04.38_51" = "side rgb s - bin4",
		"side.vis.hsv.s.normalized.histogram.bin.05.51_63" = "side rgb s - bin5",
		"side.vis.hsv.s.normalized.histogram.bin.06.63_76" = "side rgb s - bin6",
		"top.vis.hsv.s.normalized.histogram.bin.01.0_12" = "top rgb s - bin1",
		"top.vis.hsv.s.normalized.histogram.bin.02.12_25" = "top rgb s - bin2",
		"top.vis.hsv.s.normalized.histogram.bin.03.25_38" = "top rgb s - bin3",
		"top.vis.hsv.s.normalized.histogram.bin.04.38_51" = "top rgb s - bin4",
		"top.vis.hsv.s.normalized.histogram.bin.05.51_63" = "top rgb s - bin5",
		"top.vis.hsv.s.normalized.histogram.bin.06.63_76" = "top rgb s - bin6",
		"side.vis.hsv.s.normalized.kurtosis" = "side rgb s - kurtosis",
		"side.vis.hsv.s.normalized.skewness" = "side rgb s - skewness",
		"side.vis.hsv.s.normalized.stddev" = "side rgb s - stddev",
		"side.vis.hsv.s.normalized.average" = "side rgb s - average",
		"top.vis.hsv.s.normalized.kurtosis" = "top rgb s - kurtosis",
		"top.vis.hsv.s.normalized.skewness" = "top rgb s - skewness",
		"top.vis.hsv.s.normalized.stddev" = "top rgb s - stddev",
		"top.vis.hsv.s.normalized.average" = "top rgb s - average",
		
		"side.vis.hsv.v.histogram.bin.01.0_12" = "side rgb v - bin1",
		"side.vis.hsv.v.histogram.bin.02.12_25" = "side rgb v - bin2",
		"side.vis.hsv.v.histogram.bin.03.25_38" = "side rgb v - bin3",
		"side.vis.hsv.v.histogram.bin.04.38_51" = "side rgb v - bin4",
		"side.vis.hsv.v.histogram.bin.05.51_63" = "side rgb v - bin5",
		"side.vis.hsv.v.histogram.bin.06.63_76" = "side rgb v - bin6",
		"top.vis.hsv.v.histogram.bin.01.0_12" = "top rgb v - bin1",
		"top.vis.hsv.v.histogram.bin.02.12_25" = "top rgb v - bin2",
		"top.vis.hsv.v.histogram.bin.03.25_38" = "top rgb v - bin3",
		"top.vis.hsv.v.histogram.bin.04.38_51" = "top rgb v - bin4",
		"top.vis.hsv.v.histogram.bin.05.51_63" = "top rgb v - bin5",
		"top.vis.hsv.v.histogram.bin.06.63_76" = "top rgb v - bin6",
		"side.vis.hsv.v.kurtosis" = "side rgb v - kurtosis",
		"side.vis.hsv.v.skewness" = "side rgb v - skewness",
		"side.vis.hsv.v.stddev" = "side rgb v - stddev",
		"side.vis.hsv.v.average" = "side rgb v - average",
		"top.vis.hsv.v.kurtosis" = "top rgb v - kurtosis",
		"top.vis.hsv.v.skewness" = "top rgb v - skewness",
		"top.vis.hsv.v.stddev" = "top rgb v - stddev",
		"top.vis.hsv.v.average" = "top rgb v - average",
		
		"side.vis.hsv.v.normalized.histogram.bin.01.0_12" = "side rgb v - bin1",
		"side.vis.hsv.v.normalized.histogram.bin.02.12_25" = "side rgb v - bin2",
		"side.vis.hsv.v.normalized.histogram.bin.03.25_38" = "side rgb v - bin3",
		"side.vis.hsv.v.normalized.histogram.bin.04.38_51" = "side rgb v - bin4",
		"side.vis.hsv.v.normalized.histogram.bin.05.51_63" = "side rgb v - bin5",
		"side.vis.hsv.v.normalized.histogram.bin.06.63_76" = "side rgb v - bin6",
		"top.vis.hsv.v.normalized.histogram.bin.01.0_12" = "top rgb v - bin1",
		"top.vis.hsv.v.normalized.histogram.bin.02.12_25" = "top rgb v - bin2",
		"top.vis.hsv.v.normalized.histogram.bin.03.25_38" = "top rgb v - bin3",
		"top.vis.hsv.v.normalized.histogram.bin.04.38_51" = "top rgb v - bin4",
		"top.vis.hsv.v.normalized.histogram.bin.05.51_63" = "top rgb v - bin5",
		"top.vis.hsv.v.normalized.histogram.bin.06.63_76" = "top rgb v - bin6",
		"side.vis.hsv.v.normalized.kurtosis" = "side rgb v - kurtosis",
		"side.vis.hsv.v.normalized.skewness" = "side rgb v - skewness",
		"side.vis.hsv.v.normalized.stddev" = "side rgb v - stddev",
		"side.vis.hsv.v.normalized.average" = "side rgb v - average",
		"top.vis.hsv.v.normalized.kurtosis" = "top rgb v - kurtosis",
		"top.vis.hsv.v.normalized.skewness" = "top rgb v - skewness",
		"top.vis.hsv.v.normalized.stddev" = "top rgb v - stddev",
		"top.vis.hsv.v.normalized.average" = "top rgb v - average"	
)


#descriptorSet_nBoxplot = c(#"volume.my", "volume.fluo.plant_weight.iap"
#							"Weight A (g)", 
#							"Weight B (g)",
#							"Water (sum of day)",
#							#"Water (weight-diff)", 
#							"side.height.norm (mm)", 
#							"side.width.norm (mm)", 
#							
#							"side.area.norm (mm^2)", 
#							"top.area.norm (mm^2)", 											
#							"side.fluo.intensity.chlorophyl.average (relative)", 
#							"side.fluo.intensity.phenol.average (relative)", 
#							"side.nir.intensity.average (relative)",
#							
#							"top.nir.intensity.average (relative / pix)",												
#							"side.leaf.count.median (leafs)", 
#							"side.bloom.count (tassel)", 
#							"side.leaf.length.sum.norm.max (mm)", 
#							"volume.iap (px^3)", 
#							
#							"volume.lt (px^3)", 
#							"volume.iap.wue",
#							"side.area.avg.wue",
#							"side.nir.wetness.plant_weight_drought_loss", 
#							"top.nir.wetness.plant_weight_drought_loss", 
#							
#							"side.nir.wetness.average (percent)", 
#							"top.nir.wetness.average (percent)", 
#							#"side.area.relative", 
#							"side.height.norm.relative", 
#							"side.width.norm.relative", 
#							
#							"top.area.relative", 
#							"side.area.relative", 
#							"volume.iap.relative", 
#							"side.height (px)", 
#							"side.width (px)", 
#							
#							"side.area (px)", 
#							"top.area (px)",
#							############ new #######
#							"side.hull.area (px)",
#							"side.hull.area.norm (mm^2)",
#							"side.hull.pc1",
#							
#							"side.hull.pc1.norm",
#							"side.hull.pc2",
#							"side.hull.pc2.norm",
#							"side.hull.fillgrade (percent)",		
#							"top.hull.area (px)",
#							
#							"top.hull.area.norm (mm^2)",
#							"top.hull.pc1",
#							"top.hull.pc1.norm",
#							"top.hull.pc2",
#							"top.hull.pc2.norm",
#							
#							"top.hull.fillgrade (percent)",
#							"side.vis.hue.average",
#							"top.vis.hue.average",
#							"mark1.y (percent)",
#							#"mark2.y (percent)",
#							
#							"mark3.y (percent)",
#							"top.ir.intensity.average",
#							"side.ir.intensity.average",
#							"side.nir.skeleton.intensity.average (relative)",
#							"top.nir.skeleton.intensity.average",
#							
#							"side.compactness.16 (relative)",
#							"top.compactness.16 (relative)",
#							"side.hull.circularity (relative)",
#							"top.hull.circularity (relative)",
#							"side.compactness.01 (relative)",
#							
#							"top.compactness.01 (relative)",
#							"side.fluo.intensity.average (relative)",
#							"top.fluo.intensity.average (relative / pix)",
#							"side.hull.circumcircle.d (px)",
#							"top.hull.circumcircle.d (px)"
#					)
#
#	descriptorSetName_nBoxplot = c(#"digital biomass (visible light images, IAP formula) (px^3)", "yellow spectra normed to the realtionship between dry and normal"
#							"weight before watering (g)", 
#							"weight after watering (g)", 
#							"water weight (g)", 
#							"height (zoom corrected) (mm)", 
#							"width (zoom corrected) (mm)", 
#							"side area (zoom corrected) (mm^2)", 
#							"top area (zoom corrected) (mm^2)", 
#							"chlorophyll intensity (relative intensity/pixel)", 
#							"fluorescence intensity (relative intensity/pixel)", 
#							"side nir intensity (relative intensity/pixel)",
#							"top nir intensity (relative intensity/pixel)",
#							"number of leafs", 
#							"number of tassel florets", 
#							"length of leafs plus stem (mm)", 			 
#							"digital biomass (visible light images, IAP formula) (px^3)", 
#							"digital biomass (visible light, LemnaTec 0,90 formula) (px^3)", 
#							"volume based water use efficiency", 
#							"weighted loss through drought stress (side)", 
#							"weighted loss through drought stress (top)", 
#							"Average wetness of side image", 
#							"Average wetness of top image", 
#							"growth in %/day", 
#							"plant height growth rate (%/day)", 
#							"plant width growth rate (%/day)", 
#							"top area growth rate (%/day)", 
#							"side area growth rate (%/day)", 
#							"volume growth (visible light images, IAP based formula) (%/day)", 
#							"height (px)", 
#							"width (px)", 
#							"side area (px)", 
#							"top area (px)",
#							####### new #######
#							"side area of convex hull (px)",
#							"side area of convex hull (zoom corrected) (mm^2)",
#							"side maximum extension (px)",
#							"side maximum extension (zoom corrected) (mm)",
#							"opposite direction of the side maximum extension (px)",
#							"opposite direction of the side maximum extension (zoom corrected) (mm)",
#							"fillgrade of side convex hull (%)",
#							"top area of convex hull (px)",
#							"top area of convex hull (zoom corrected) (mm^2)",
#							"top maximum extension (px)",
#							"top maximum extension (zoom corrected) (mm)",
#							"opposite direction of the top maximum extension (px)",
#							"opposite direction of the top maximum extension (zoom corrected) (mm)",
#							"fillgrade of top convex hull (%)",
#							"side visible hue average value",
#							"top visible hue average value",
#							"blue marker position from top (%)",
#							"blue marker position from middle (%)",
#							"blue marker position from bottom  (%)",
#							"top ir intensity",
#							"side ir intensity"
#					)							
					