// ==============================================================================
//
// SelectionEditComponent.java
//
// Copyright (c) 2001-2004 Gravisto Team, University of Passau
//
// ==============================================================================
// $Id: SelectionEditComponent.java,v 1.1 2011-01-31 09:04:30 klukas Exp $

/* Generated by Together */
package org.graffiti.plugin.editcomponent;

import javax.swing.JComboBox;
import javax.swing.JComponent;

import org.graffiti.graph.GraphElement;
import org.graffiti.plugin.Displayable;
import org.graffiti.selection.Selection;

/**
 * This class provides an edit component for selections.
 * 
 * @see org.graffiti.selection.Selection
 * @see GraphComponentEditComponent
 */
public class SelectionEditComponent
					extends GraphComponentEditComponent {
	// ~ Instance fields ========================================================
	
	/** The <code>Selection</code> of this edit component. */
	private Selection selection;
	
	// ~ Constructors ===========================================================
	
	/**
	 * Constructs a new <code>SelectionEditComponent</code>.
	 * 
	 * @param disp
	 *           DOCUMENT ME!
	 */
	public SelectionEditComponent(Displayable disp) {
		super(disp);
	}
	
	// ~ Methods ================================================================
	
	/**
	 * Returns a String suitable for the name column in the name value table.
	 * 
	 * @return a String suitable for the name column in the name value table.
	 */
	public String getCaption() {
		return selection.getName();
	}
	
	/**
	 * Returns the <code>ValueEditComponent</code>'s <code>JComponent</code>.
	 * 
	 * @return DOCUMENT ME!
	 * @throws RuntimeException
	 *            DOCUMENT ME!
	 */
	public JComponent getComponent() {
		// throw new RuntimeException("implement me");
		return new JComboBox(selection.getNodes().toArray());
	}
	
	/*
	 * (non-Javadoc)
	 * @see org.graffiti.plugin.editcomponent.GraphComponentEditComponent#setGraphComponent()
	 */
	public void setGraphComponent() {
		//
		
	}
	
	/*
	 * (non-Javadoc)
	 * @see org.graffiti.plugin.editcomponent.ValueEditComponent#setEditFieldValue()
	 */
	public void setEditFieldValue() {
		//
		
	}
	
	/*
	 * (non-Javadoc)
	 * @see org.graffiti.plugin.editcomponent.ValueEditComponent#setValue()
	 */
	public void setValue() {
		//
		
	}
	
	/*
	 * (non-Javadoc)
	 * @see org.graffiti.plugin.editcomponent.GraphComponentEditComponent#setGraphElement(org.graffiti.graph.GraphElement)
	 */
	@Override
	public void setGraphElement(GraphElement graphElement) {
		selection.clear();
		selection.add(graphElement);
	}
}

// ------------------------------------------------------------------------------
// end of file
// ------------------------------------------------------------------------------
