/*
 * ----------------------------------------------------------------------------
 * This file was automatically generated by SWIG (http://www.swig.org).
 * Version 1.3.31
 * Do not make changes to this file unless you know what you are doing--modify
 * the SWIG interface file instead.
 * -----------------------------------------------------------------------------
 */

package colajava;

public class AlignmentConstraintPair {
	private long swigCPtr;
	protected boolean swigCMemOwn;
	
	protected AlignmentConstraintPair(long cPtr, boolean cMemoryOwn) {
		swigCMemOwn = cMemoryOwn;
		swigCPtr = cPtr;
	}
	
	protected static long getCPtr(AlignmentConstraintPair obj) {
		return (obj == null) ? 0 : obj.swigCPtr;
	}
	
	@Override
	protected void finalize() {
		delete();
	}
	
	public synchronized void delete() {
		if (swigCPtr != 0 && swigCMemOwn) {
			swigCMemOwn = false;
			colaJNI.delete_AlignmentConstraintPair(swigCPtr);
		}
		swigCPtr = 0;
	}
	
	public AlignmentConstraintPair() {
		this(colaJNI.new_AlignmentConstraintPair__SWIG_0(), true);
	}
	
	public AlignmentConstraintPair(AlignmentConstraint first, AlignmentConstraint second) {
		this(colaJNI.new_AlignmentConstraintPair__SWIG_1(AlignmentConstraint.getCPtr(first), first, AlignmentConstraint.getCPtr(second), second), true);
	}
	
	public AlignmentConstraintPair(AlignmentConstraintPair p) {
		this(colaJNI.new_AlignmentConstraintPair__SWIG_2(AlignmentConstraintPair.getCPtr(p), p), true);
	}
	
	public void setFirst(AlignmentConstraint value) {
		colaJNI.AlignmentConstraintPair_first_set(swigCPtr, this, AlignmentConstraint.getCPtr(value), value);
	}
	
	public AlignmentConstraint getFirst() {
		long cPtr = colaJNI.AlignmentConstraintPair_first_get(swigCPtr, this);
		return (cPtr == 0) ? null : new AlignmentConstraint(cPtr, false);
	}
	
	public void setSecond(AlignmentConstraint value) {
		colaJNI.AlignmentConstraintPair_second_set(swigCPtr, this, AlignmentConstraint.getCPtr(value), value);
	}
	
	public AlignmentConstraint getSecond() {
		long cPtr = colaJNI.AlignmentConstraintPair_second_get(swigCPtr, this);
		return (cPtr == 0) ? null : new AlignmentConstraint(cPtr, false);
	}
	
}
