/*
 * ----------------------------------------------------------------------------
 * This file was automatically generated by SWIG (http://www.swig.org).
 * Version 1.3.31
 * Do not make changes to this file unless you know what you are doing--modify
 * the SWIG interface file instead.
 * -----------------------------------------------------------------------------
 */

package colajava;

public class ConvexCluster extends Cluster {
	private long swigCPtr;
	
	protected ConvexCluster(long cPtr, boolean cMemoryOwn) {
		super(colaJNI.SWIGConvexClusterUpcast(cPtr), cMemoryOwn);
		swigCPtr = cPtr;
	}
	
	protected static long getCPtr(ConvexCluster obj) {
		return (obj == null) ? 0 : obj.swigCPtr;
	}
	
	@Override
	protected void finalize() {
		delete();
	}
	
	@Override
	public synchronized void delete() {
		if (swigCPtr != 0 && swigCMemOwn) {
			swigCMemOwn = false;
			colaJNI.delete_ConvexCluster(swigCPtr);
		}
		swigCPtr = 0;
		super.delete();
	}
	
	@Override
	public void computeBoundary(RectPtrVector rs) {
		colaJNI.ConvexCluster_computeBoundary(swigCPtr, this, RectPtrVector.getCPtr(rs), rs);
	}
	
	public void setHullRIDs(SWIGTYPE_p_std__valarrayTunsigned_int_t value) {
		colaJNI.ConvexCluster_hullRIDs_set(swigCPtr, this, SWIGTYPE_p_std__valarrayTunsigned_int_t.getCPtr(value));
	}
	
	public SWIGTYPE_p_std__valarrayTunsigned_int_t getHullRIDs() {
		return new SWIGTYPE_p_std__valarrayTunsigned_int_t(colaJNI.ConvexCluster_hullRIDs_get(swigCPtr, this), true);
	}
	
	public void setHullCorners(SWIGTYPE_p_std__valarrayTunsigned_char_t value) {
		colaJNI.ConvexCluster_hullCorners_set(swigCPtr, this, SWIGTYPE_p_std__valarrayTunsigned_char_t.getCPtr(value));
	}
	
	public SWIGTYPE_p_std__valarrayTunsigned_char_t getHullCorners() {
		return new SWIGTYPE_p_std__valarrayTunsigned_char_t(colaJNI.ConvexCluster_hullCorners_get(swigCPtr, this), true);
	}
	
	public ConvexCluster() {
		this(colaJNI.new_ConvexCluster(), true);
	}
	
}
