// ==============================================================================
//
// View3D.java
//
// Copyright (c) 2001-2004 Gravisto Team, University of Passau
//
// ==============================================================================
// $Id: View3D.java,v 1.1 2011-01-31 09:04:23 klukas Exp $

/* Generated by Together */
package org.graffiti.plugin.view;

/**
 * DOCUMENT ME!
 * 
 * @author $Author: klukas $
 * @version $Revision: 1.1 $
 */
public interface View3D
					extends View {}

// ------------------------------------------------------------------------------
// end of file
// ------------------------------------------------------------------------------
