/*
 * ----------------------------------------------------------------------------
 * This file was automatically generated by SWIG (http://www.swig.org).
 * Version 1.3.31
 * Do not make changes to this file unless you know what you are doing--modify
 * the SWIG interface file instead.
 * -----------------------------------------------------------------------------
 */

package colajava;

public class DesiredPosition {
	private long swigCPtr;
	protected boolean swigCMemOwn;
	
	protected DesiredPosition(long cPtr, boolean cMemoryOwn) {
		swigCMemOwn = cMemoryOwn;
		swigCPtr = cPtr;
	}
	
	protected static long getCPtr(DesiredPosition obj) {
		return (obj == null) ? 0 : obj.swigCPtr;
	}
	
	@Override
	protected void finalize() {
		delete();
	}
	
	public synchronized void delete() {
		if (swigCPtr != 0 && swigCMemOwn) {
			swigCMemOwn = false;
			colaJNI.delete_DesiredPosition(swigCPtr);
		}
		swigCPtr = 0;
	}
	
	public void setId(long value) {
		colaJNI.DesiredPosition_id_set(swigCPtr, this, value);
	}
	
	public long getId() {
		return colaJNI.DesiredPosition_id_get(swigCPtr, this);
	}
	
	public void setX(double value) {
		colaJNI.DesiredPosition_x_set(swigCPtr, this, value);
	}
	
	public double getX() {
		return colaJNI.DesiredPosition_x_get(swigCPtr, this);
	}
	
	public void setY(double value) {
		colaJNI.DesiredPosition_y_set(swigCPtr, this, value);
	}
	
	public double getY() {
		return colaJNI.DesiredPosition_y_get(swigCPtr, this);
	}
	
	public void setWeight(double value) {
		colaJNI.DesiredPosition_weight_set(swigCPtr, this, value);
	}
	
	public double getWeight() {
		return colaJNI.DesiredPosition_weight_get(swigCPtr, this);
	}
	
	public DesiredPosition() {
		this(colaJNI.new_DesiredPosition(), true);
	}
	
}
