/*
 * ----------------------------------------------------------------------------
 * This file was automatically generated by SWIG (http://www.swig.org).
 * Version 1.3.31
 * Do not make changes to this file unless you know what you are doing--modify
 * the SWIG interface file instead.
 * -----------------------------------------------------------------------------
 */

package colajava;

public class Point {
	private long swigCPtr;
	protected boolean swigCMemOwn;
	
	protected Point(long cPtr, boolean cMemoryOwn) {
		swigCMemOwn = cMemoryOwn;
		swigCPtr = cPtr;
	}
	
	protected static long getCPtr(Point obj) {
		return (obj == null) ? 0 : obj.swigCPtr;
	}
	
	@Override
	protected void finalize() {
		delete();
	}
	
	public synchronized void delete() {
		if (swigCPtr != 0 && swigCMemOwn) {
			swigCMemOwn = false;
			colaJNI.delete_Point(swigCPtr);
		}
		swigCPtr = 0;
	}
	
	public Point() {
		this(colaJNI.new_Point__SWIG_0(), true);
	}
	
	public Point(double xv, double yv) {
		this(colaJNI.new_Point__SWIG_1(xv, yv), true);
	}
	
	public void setX(double value) {
		colaJNI.Point_x_set(swigCPtr, this, value);
	}
	
	public double getX() {
		return colaJNI.Point_x_get(swigCPtr, this);
	}
	
	public void setY(double value) {
		colaJNI.Point_y_set(swigCPtr, this, value);
	}
	
	public double getY() {
		return colaJNI.Point_y_get(swigCPtr, this);
	}
	
	public void setId(long value) {
		colaJNI.Point_id_set(swigCPtr, this, value);
	}
	
	public long getId() {
		return colaJNI.Point_id_get(swigCPtr, this);
	}
	
	public void setVn(int value) {
		colaJNI.Point_vn_set(swigCPtr, this, value);
	}
	
	public int getVn() {
		return colaJNI.Point_vn_get(swigCPtr, this);
	}
	
}
