/*
 * ----------------------------------------------------------------------------
 * This file was automatically generated by SWIG (http://www.swig.org).
 * Version 1.3.31
 * Do not make changes to this file unless you know what you are doing--modify
 * the SWIG interface file instead.
 * -----------------------------------------------------------------------------
 */

package colajava;

public class Router {
	private long swigCPtr;
	protected boolean swigCMemOwn;
	
	protected Router(long cPtr, boolean cMemoryOwn) {
		swigCMemOwn = cMemoryOwn;
		swigCPtr = cPtr;
	}
	
	protected static long getCPtr(Router obj) {
		return (obj == null) ? 0 : obj.swigCPtr;
	}
	
	@Override
	protected void finalize() {
		delete();
	}
	
	public synchronized void delete() {
		if (swigCPtr != 0 && swigCMemOwn) {
			swigCMemOwn = false;
			colaJNI.delete_Router(swigCPtr);
		}
		swigCPtr = 0;
	}
	
	public Router() {
		this(colaJNI.new_Router(), true);
	}
	
	public void setShapeRefs(SWIGTYPE_p_ShapeRefList value) {
		colaJNI.Router_shapeRefs_set(swigCPtr, this, SWIGTYPE_p_ShapeRefList.getCPtr(value));
	}
	
	public SWIGTYPE_p_ShapeRefList getShapeRefs() {
		return new SWIGTYPE_p_ShapeRefList(colaJNI.Router_shapeRefs_get(swigCPtr, this), true);
	}
	
	public void setConnRefs(SWIGTYPE_p_std__listTAvoid__ConnRef_p_t value) {
		colaJNI.Router_connRefs_set(swigCPtr, this, SWIGTYPE_p_std__listTAvoid__ConnRef_p_t.getCPtr(value));
	}
	
	public SWIGTYPE_p_std__listTAvoid__ConnRef_p_t getConnRefs() {
		long cPtr = colaJNI.Router_connRefs_get(swigCPtr, this);
		return (cPtr == 0) ? null : new SWIGTYPE_p_std__listTAvoid__ConnRef_p_t(cPtr, false);
	}
	
	public void setClusterRefs(SWIGTYPE_p_ClusterRefList value) {
		colaJNI.Router_clusterRefs_set(swigCPtr, this, SWIGTYPE_p_ClusterRefList.getCPtr(value));
	}
	
	public SWIGTYPE_p_ClusterRefList getClusterRefs() {
		return new SWIGTYPE_p_ClusterRefList(colaJNI.Router_clusterRefs_get(swigCPtr, this), true);
	}
	
	public void setVisGraph(SWIGTYPE_p_EdgeList value) {
		colaJNI.Router_visGraph_set(swigCPtr, this, SWIGTYPE_p_EdgeList.getCPtr(value));
	}
	
	public SWIGTYPE_p_EdgeList getVisGraph() {
		return new SWIGTYPE_p_EdgeList(colaJNI.Router_visGraph_get(swigCPtr, this), true);
	}
	
	public void setInvisGraph(SWIGTYPE_p_EdgeList value) {
		colaJNI.Router_invisGraph_set(swigCPtr, this, SWIGTYPE_p_EdgeList.getCPtr(value));
	}
	
	public SWIGTYPE_p_EdgeList getInvisGraph() {
		return new SWIGTYPE_p_EdgeList(colaJNI.Router_invisGraph_get(swigCPtr, this), true);
	}
	
	public void setContains(SWIGTYPE_p_ContainsMap value) {
		colaJNI.Router_contains_set(swigCPtr, this, SWIGTYPE_p_ContainsMap.getCPtr(value));
	}
	
	public SWIGTYPE_p_ContainsMap getContains() {
		return new SWIGTYPE_p_ContainsMap(colaJNI.Router_contains_get(swigCPtr, this), true);
	}
	
	public void setVertices(SWIGTYPE_p_VertInfList value) {
		colaJNI.Router_vertices_set(swigCPtr, this, SWIGTYPE_p_VertInfList.getCPtr(value));
	}
	
	public SWIGTYPE_p_VertInfList getVertices() {
		return new SWIGTYPE_p_VertInfList(colaJNI.Router_vertices_get(swigCPtr, this), true);
	}
	
	public void setEnclosingClusters(SWIGTYPE_p_ContainsMap value) {
		colaJNI.Router_enclosingClusters_set(swigCPtr, this, SWIGTYPE_p_ContainsMap.getCPtr(value));
	}
	
	public SWIGTYPE_p_ContainsMap getEnclosingClusters() {
		return new SWIGTYPE_p_ContainsMap(colaJNI.Router_enclosingClusters_get(swigCPtr, this), true);
	}
	
	public void setPartialTime(boolean value) {
		colaJNI.Router_PartialTime_set(swigCPtr, this, value);
	}
	
	public boolean getPartialTime() {
		return colaJNI.Router_PartialTime_get(swigCPtr, this);
	}
	
	public void setSimpleRouting(boolean value) {
		colaJNI.Router_SimpleRouting_set(swigCPtr, this, value);
	}
	
	public boolean getSimpleRouting() {
		return colaJNI.Router_SimpleRouting_get(swigCPtr, this);
	}
	
	public void setSegmt_penalty(double value) {
		colaJNI.Router_segmt_penalty_set(swigCPtr, this, value);
	}
	
	public double getSegmt_penalty() {
		return colaJNI.Router_segmt_penalty_get(swigCPtr, this);
	}
	
	public void setAngle_penalty(double value) {
		colaJNI.Router_angle_penalty_set(swigCPtr, this, value);
	}
	
	public double getAngle_penalty() {
		return colaJNI.Router_angle_penalty_get(swigCPtr, this);
	}
	
	public void setCrossing_penalty(double value) {
		colaJNI.Router_crossing_penalty_set(swigCPtr, this, value);
	}
	
	public double getCrossing_penalty() {
		return colaJNI.Router_crossing_penalty_get(swigCPtr, this);
	}
	
	public void setCluster_crossing_penalty(double value) {
		colaJNI.Router_cluster_crossing_penalty_set(swigCPtr, this, value);
	}
	
	public double getCluster_crossing_penalty() {
		return colaJNI.Router_cluster_crossing_penalty_get(swigCPtr, this);
	}
	
	public void setUseAStarSearch(boolean value) {
		colaJNI.Router_UseAStarSearch_set(swigCPtr, this, value);
	}
	
	public boolean getUseAStarSearch() {
		return colaJNI.Router_UseAStarSearch_get(swigCPtr, this);
	}
	
	public void setIgnoreRegions(boolean value) {
		colaJNI.Router_IgnoreRegions_set(swigCPtr, this, value);
	}
	
	public boolean getIgnoreRegions() {
		return colaJNI.Router_IgnoreRegions_get(swigCPtr, this);
	}
	
	public void setSelectiveReroute(boolean value) {
		colaJNI.Router_SelectiveReroute_set(swigCPtr, this, value);
	}
	
	public boolean getSelectiveReroute() {
		return colaJNI.Router_SelectiveReroute_get(swigCPtr, this);
	}
	
	public void setIncludeEndpoints(boolean value) {
		colaJNI.Router_IncludeEndpoints_set(swigCPtr, this, value);
	}
	
	public boolean getIncludeEndpoints() {
		return colaJNI.Router_IncludeEndpoints_get(swigCPtr, this);
	}
	
	public void setUseLeesAlgorithm(boolean value) {
		colaJNI.Router_UseLeesAlgorithm_set(swigCPtr, this, value);
	}
	
	public boolean getUseLeesAlgorithm() {
		return colaJNI.Router_UseLeesAlgorithm_get(swigCPtr, this);
	}
	
	public void setInvisibilityGrph(boolean value) {
		colaJNI.Router_InvisibilityGrph_set(swigCPtr, this, value);
	}
	
	public boolean getInvisibilityGrph() {
		return colaJNI.Router_InvisibilityGrph_get(swigCPtr, this);
	}
	
	public void setConsolidateMoves(boolean value) {
		colaJNI.Router_ConsolidateMoves_set(swigCPtr, this, value);
	}
	
	public boolean getConsolidateMoves() {
		return colaJNI.Router_ConsolidateMoves_get(swigCPtr, this);
	}
	
	public void setPartialFeedback(boolean value) {
		colaJNI.Router_PartialFeedback_set(swigCPtr, this, value);
	}
	
	public boolean getPartialFeedback() {
		return colaJNI.Router_PartialFeedback_get(swigCPtr, this);
	}
	
	public void setRubberBandRouting(boolean value) {
		colaJNI.Router_RubberBandRouting_set(swigCPtr, this, value);
	}
	
	public boolean getRubberBandRouting() {
		return colaJNI.Router_RubberBandRouting_get(swigCPtr, this);
	}
	
	public void setTimers(SWIGTYPE_p_Timer value) {
		colaJNI.Router_timers_set(swigCPtr, this, SWIGTYPE_p_Timer.getCPtr(value));
	}
	
	public SWIGTYPE_p_Timer getTimers() {
		return new SWIGTYPE_p_Timer(colaJNI.Router_timers_get(swigCPtr, this), true);
	}
	
	public void setSt_checked_edges(int value) {
		colaJNI.Router_st_checked_edges_set(swigCPtr, this, value);
	}
	
	public int getSt_checked_edges() {
		return colaJNI.Router_st_checked_edges_get(swigCPtr, this);
	}
	
	public void addShape(SWIGTYPE_p_ShapeRef shape) {
		colaJNI.Router_addShape(swigCPtr, this, SWIGTYPE_p_ShapeRef.getCPtr(shape));
	}
	
	public void delShape(SWIGTYPE_p_ShapeRef shape) {
		colaJNI.Router_delShape(swigCPtr, this, SWIGTYPE_p_ShapeRef.getCPtr(shape));
	}
	
	public void moveShape(SWIGTYPE_p_ShapeRef shape, Polygon newPoly, boolean first_move) {
		colaJNI.Router_moveShape__SWIG_0(swigCPtr, this, SWIGTYPE_p_ShapeRef.getCPtr(shape), Polygon.getCPtr(newPoly), newPoly, first_move);
	}
	
	public void moveShape(SWIGTYPE_p_ShapeRef shape, Polygon newPoly) {
		colaJNI.Router_moveShape__SWIG_1(swigCPtr, this, SWIGTYPE_p_ShapeRef.getCPtr(shape), Polygon.getCPtr(newPoly), newPoly);
	}
	
	public void processMoves() {
		colaJNI.Router_processMoves(swigCPtr, this);
	}
	
	public void addCluster(SWIGTYPE_p_ClusterRef cluster) {
		colaJNI.Router_addCluster(swigCPtr, this, SWIGTYPE_p_ClusterRef.getCPtr(cluster));
	}
	
	public void delCluster(SWIGTYPE_p_ClusterRef cluster) {
		colaJNI.Router_delCluster(swigCPtr, this, SWIGTYPE_p_ClusterRef.getCPtr(cluster));
	}
	
	public void attachedConns(SWIGTYPE_p_std__listTunsigned_int_t conns, long shapeId, long type) {
		colaJNI.Router_attachedConns(swigCPtr, this, SWIGTYPE_p_std__listTunsigned_int_t.getCPtr(conns), shapeId, type);
	}
	
	public void attachedShapes(SWIGTYPE_p_std__listTunsigned_int_t shapes, long shapeId, long type) {
		colaJNI.Router_attachedShapes(swigCPtr, this, SWIGTYPE_p_std__listTunsigned_int_t.getCPtr(shapes), shapeId, type);
	}
	
	public void markConnectors(SWIGTYPE_p_ShapeRef shape) {
		colaJNI.Router_markConnectors(swigCPtr, this, SWIGTYPE_p_ShapeRef.getCPtr(shape));
	}
	
	public void generateContains(SWIGTYPE_p_VertInf pt) {
		colaJNI.Router_generateContains(swigCPtr, this, SWIGTYPE_p_VertInf.getCPtr(pt));
	}
	
	public void printInfo() {
		colaJNI.Router_printInfo(swigCPtr, this);
	}
	
}
