/*
 * ----------------------------------------------------------------------------
 * This file was automatically generated by SWIG (http://www.swig.org).
 * Version 1.3.31
 * Do not make changes to this file unless you know what you are doing--modify
 * the SWIG interface file instead.
 * -----------------------------------------------------------------------------
 */

package colajava;

public class ColaResizes {
	private long swigCPtr;
	protected boolean swigCMemOwn;
	
	protected ColaResizes(long cPtr, boolean cMemoryOwn) {
		swigCMemOwn = cMemoryOwn;
		swigCPtr = cPtr;
	}
	
	protected static long getCPtr(ColaResizes obj) {
		return (obj == null) ? 0 : obj.swigCPtr;
	}
	
	@Override
	protected void finalize() {
		delete();
	}
	
	public synchronized void delete() {
		if (swigCPtr != 0 && swigCMemOwn) {
			swigCMemOwn = false;
			colaJNI.delete_ColaResizes(swigCPtr);
		}
		swigCPtr = 0;
	}
	
	public ColaResizes() {
		this(colaJNI.new_ColaResizes__SWIG_0(), true);
	}
	
	public ColaResizes(long n) {
		this(colaJNI.new_ColaResizes__SWIG_1(n), true);
	}
	
	public long size() {
		return colaJNI.ColaResizes_size(swigCPtr, this);
	}
	
	public long capacity() {
		return colaJNI.ColaResizes_capacity(swigCPtr, this);
	}
	
	public void reserve(long n) {
		colaJNI.ColaResizes_reserve(swigCPtr, this, n);
	}
	
	public boolean isEmpty() {
		return colaJNI.ColaResizes_isEmpty(swigCPtr, this);
	}
	
	public void clear() {
		colaJNI.ColaResizes_clear(swigCPtr, this);
	}
	
	public void add(Resize x) {
		colaJNI.ColaResizes_add(swigCPtr, this, Resize.getCPtr(x), x);
	}
	
	public Resize get(int i) {
		return new Resize(colaJNI.ColaResizes_get(swigCPtr, this, i), false);
	}
	
	public void set(int i, Resize x) {
		colaJNI.ColaResizes_set(swigCPtr, this, i, Resize.getCPtr(x), x);
	}
	
}
