/*
 * ----------------------------------------------------------------------------
 * This file was automatically generated by SWIG (http://www.swig.org).
 * Version 1.3.31
 * Do not make changes to this file unless you know what you are doing--modify
 * the SWIG interface file instead.
 * -----------------------------------------------------------------------------
 */

package colajava;

public class EdgeVector {
	private long swigCPtr;
	protected boolean swigCMemOwn;
	
	protected EdgeVector(long cPtr, boolean cMemoryOwn) {
		swigCMemOwn = cMemoryOwn;
		swigCPtr = cPtr;
	}
	
	protected static long getCPtr(EdgeVector obj) {
		return (obj == null) ? 0 : obj.swigCPtr;
	}
	
	@Override
	protected void finalize() {
		delete();
	}
	
	public synchronized void delete() {
		if (swigCPtr != 0 && swigCMemOwn) {
			swigCMemOwn = false;
			colaJNI.delete_EdgeVector(swigCPtr);
		}
		swigCPtr = 0;
	}
	
	public EdgeVector() {
		this(colaJNI.new_EdgeVector__SWIG_0(), true);
	}
	
	public EdgeVector(long n) {
		this(colaJNI.new_EdgeVector__SWIG_1(n), true);
	}
	
	public long size() {
		return colaJNI.EdgeVector_size(swigCPtr, this);
	}
	
	public long capacity() {
		return colaJNI.EdgeVector_capacity(swigCPtr, this);
	}
	
	public void reserve(long n) {
		colaJNI.EdgeVector_reserve(swigCPtr, this, n);
	}
	
	public boolean isEmpty() {
		return colaJNI.EdgeVector_isEmpty(swigCPtr, this);
	}
	
	public void clear() {
		colaJNI.EdgeVector_clear(swigCPtr, this);
	}
	
	public void add(ColaEdge x) {
		colaJNI.EdgeVector_add(swigCPtr, this, ColaEdge.getCPtr(x), x);
	}
	
	public ColaEdge get(int i) {
		return new ColaEdge(colaJNI.EdgeVector_get(swigCPtr, this, i), false);
	}
	
	public void set(int i, ColaEdge x) {
		colaJNI.EdgeVector_set(swigCPtr, this, i, ColaEdge.getCPtr(x), x);
	}
	
}
