/*
 * ----------------------------------------------------------------------------
 * This file was automatically generated by SWIG (http://www.swig.org).
 * Version 1.3.31
 * Do not make changes to this file unless you know what you are doing--modify
 * the SWIG interface file instead.
 * -----------------------------------------------------------------------------
 */

package colajava;

public class PtOrder {
	private long swigCPtr;
	protected boolean swigCMemOwn;
	
	protected PtOrder(long cPtr, boolean cMemoryOwn) {
		swigCMemOwn = cMemoryOwn;
		swigCPtr = cPtr;
	}
	
	protected static long getCPtr(PtOrder obj) {
		return (obj == null) ? 0 : obj.swigCPtr;
	}
	
	@Override
	protected void finalize() {
		delete();
	}
	
	public synchronized void delete() {
		if (swigCPtr != 0 && swigCMemOwn) {
			swigCMemOwn = false;
			colaJNI.delete_PtOrder(swigCPtr);
		}
		swigCPtr = 0;
	}
	
	public PtOrder() {
		this(colaJNI.new_PtOrder(), true);
	}
	
	public boolean addPoints(SWIGTYPE_p_Point innerArg, SWIGTYPE_p_Point outerArg, boolean swapped) {
		return colaJNI.PtOrder_addPoints(swigCPtr, this, SWIGTYPE_p_Point.getCPtr(innerArg), SWIGTYPE_p_Point.getCPtr(outerArg), swapped);
	}
	
	public void sort() {
		colaJNI.PtOrder_sort(swigCPtr, this);
	}
	
	public void setConnList(SWIGTYPE_p_std__listTAvoid__PointRep_p_t value) {
		colaJNI.PtOrder_connList_set(swigCPtr, this, SWIGTYPE_p_std__listTAvoid__PointRep_p_t.getCPtr(value));
	}
	
	public SWIGTYPE_p_std__listTAvoid__PointRep_p_t getConnList() {
		long cPtr = colaJNI.PtOrder_connList_get(swigCPtr, this);
		return (cPtr == 0) ? null : new SWIGTYPE_p_std__listTAvoid__PointRep_p_t(cPtr, false);
	}
	
}
