/*
 * ----------------------------------------------------------------------------
 * This file was automatically generated by SWIG (http://www.swig.org).
 * Version 1.3.31
 * Do not make changes to this file unless you know what you are doing--modify
 * the SWIG interface file instead.
 * -----------------------------------------------------------------------------
 */

package colajava;

public class ShapeRef {
	private long swigCPtr;
	protected boolean swigCMemOwn;
	
	protected ShapeRef(long cPtr, boolean cMemoryOwn) {
		swigCMemOwn = cMemoryOwn;
		swigCPtr = cPtr;
	}
	
	protected static long getCPtr(ShapeRef obj) {
		return (obj == null) ? 0 : obj.swigCPtr;
	}
	
	@Override
	protected void finalize() {
		delete();
	}
	
	public synchronized void delete() {
		if (swigCPtr != 0 && swigCMemOwn) {
			swigCMemOwn = false;
			colaJNI.delete_ShapeRef(swigCPtr);
		}
		swigCPtr = 0;
	}
	
	public ShapeRef(Router router, long id, Polygon poly) {
		this(colaJNI.new_ShapeRef(Router.getCPtr(router), router, id, Polygon.getCPtr(poly), poly), true);
	}
	
	public void setNewPoly(Polygon poly) {
		colaJNI.ShapeRef_setNewPoly(swigCPtr, this, Polygon.getCPtr(poly), poly);
	}
	
	public SWIGTYPE_p_Avoid__VertInf firstVert() {
		long cPtr = colaJNI.ShapeRef_firstVert(swigCPtr, this);
		return (cPtr == 0) ? null : new SWIGTYPE_p_Avoid__VertInf(cPtr, false);
	}
	
	public SWIGTYPE_p_Avoid__VertInf lastVert() {
		long cPtr = colaJNI.ShapeRef_lastVert(swigCPtr, this);
		return (cPtr == 0) ? null : new SWIGTYPE_p_Avoid__VertInf(cPtr, false);
	}
	
	public long id() {
		return colaJNI.ShapeRef_id(swigCPtr, this);
	}
	
	public Polygon poly() {
		return new Polygon(colaJNI.ShapeRef_poly(swigCPtr, this), false);
	}
	
	public Router router() {
		long cPtr = colaJNI.ShapeRef_router(swigCPtr, this);
		return (cPtr == 0) ? null : new Router(cPtr, false);
	}
	
	public void boundingBox(Avoid_Edge bbox) {
		colaJNI.ShapeRef_boundingBox(swigCPtr, this, Avoid_Edge.getCPtr(bbox), bbox);
	}
	
	public void makeActive() {
		colaJNI.ShapeRef_makeActive(swigCPtr, this);
	}
	
	public void makeInactive() {
		colaJNI.ShapeRef_makeInactive(swigCPtr, this);
	}
	
	public void removeFromGraph() {
		colaJNI.ShapeRef_removeFromGraph(swigCPtr, this);
	}
	
	public void markForMove() {
		colaJNI.ShapeRef_markForMove(swigCPtr, this);
	}
	
	public void clearMoveMark() {
		colaJNI.ShapeRef_clearMoveMark(swigCPtr, this);
	}
	
	public SWIGTYPE_p_Avoid__VertInf getPointVertex(Point point) {
		long cPtr = colaJNI.ShapeRef_getPointVertex(swigCPtr, this, Point.getCPtr(point), point);
		return (cPtr == 0) ? null : new SWIGTYPE_p_Avoid__VertInf(cPtr, false);
	}
	
}
