/*
 * ----------------------------------------------------------------------------
 * This file was automatically generated by SWIG (http://www.swig.org).
 * Version 1.3.31
 * Do not make changes to this file unless you know what you are doing--modify
 * the SWIG interface file instead.
 * -----------------------------------------------------------------------------
 */

package colajava;

public class Edge {
	private long swigCPtr;
	protected boolean swigCMemOwn;
	
	protected Edge(long cPtr, boolean cMemoryOwn) {
		swigCMemOwn = cMemoryOwn;
		swigCPtr = cPtr;
	}
	
	protected static long getCPtr(Edge obj) {
		return (obj == null) ? 0 : obj.swigCPtr;
	}
	
	@Override
	protected void finalize() {
		delete();
	}
	
	public synchronized void delete() {
		if (swigCPtr != 0 && swigCMemOwn) {
			swigCMemOwn = false;
			colaJNI.delete_Edge(swigCPtr);
		}
		swigCPtr = 0;
	}
	
	public void setId(long value) {
		colaJNI.Edge_id_set(swigCPtr, this, value);
	}
	
	public long getId() {
		return colaJNI.Edge_id_get(swigCPtr, this);
	}
	
	public void setIdealLength(double value) {
		colaJNI.Edge_idealLength_set(swigCPtr, this, value);
	}
	
	public double getIdealLength() {
		return colaJNI.Edge_idealLength_get(swigCPtr, this);
	}
	
	public void setNSegments(long value) {
		colaJNI.Edge_nSegments_set(swigCPtr, this, value);
	}
	
	public long getNSegments() {
		return colaJNI.Edge_nSegments_get(swigCPtr, this);
	}
	
	public Edge(long id, double idealLength, TopologyEdgePointPtrVector vs) {
		this(colaJNI.new_Edge(id, idealLength, TopologyEdgePointPtrVector.getCPtr(vs), vs), true);
	}
	
	public double pathLength() {
		return colaJNI.Edge_pathLength(swigCPtr, this);
	}
	
	public void getPath(TopologyEdgePointConstPtrVector vs) {
		colaJNI.Edge_getPath(swigCPtr, this, TopologyEdgePointConstPtrVector.getCPtr(vs), vs);
	}
	
	public boolean assertConvexBends() {
		return colaJNI.Edge_assertConvexBends(swigCPtr, this);
	}
	
	public boolean cycle() {
		return colaJNI.Edge_cycle(swigCPtr, this);
	}
	
}
