/*
 * ----------------------------------------------------------------------------
 * This file was automatically generated by SWIG (http://www.swig.org).
 * Version 1.3.31
 * Do not make changes to this file unless you know what you are doing--modify
 * the SWIG interface file instead.
 * -----------------------------------------------------------------------------
 */

package colajava;

public class Node {
	private long swigCPtr;
	protected boolean swigCMemOwn;
	
	protected Node(long cPtr, boolean cMemoryOwn) {
		swigCMemOwn = cMemoryOwn;
		swigCPtr = cPtr;
	}
	
	protected static long getCPtr(Node obj) {
		return (obj == null) ? 0 : obj.swigCPtr;
	}
	
	@Override
	protected void finalize() {
		delete();
	}
	
	public synchronized void delete() {
		if (swigCPtr != 0 && swigCMemOwn) {
			swigCMemOwn = false;
			colaJNI.delete_Node(swigCPtr);
		}
		swigCPtr = 0;
	}
	
	public long getId() {
		return colaJNI.Node_id_get(swigCPtr, this);
	}
	
	public void setRect(Rectangle value) {
		colaJNI.Node_rect_set(swigCPtr, this, Rectangle.getCPtr(value), value);
	}
	
	public Rectangle getRect() {
		long cPtr = colaJNI.Node_rect_get(swigCPtr, this);
		return (cPtr == 0) ? null : new Rectangle(cPtr, false);
	}
	
	public Node(long id, Rectangle arg1, SWIGTYPE_p_vpsc__Variable arg2) {
		this(colaJNI.new_Node__SWIG_0(id, Rectangle.getCPtr(arg1), arg1, SWIGTYPE_p_vpsc__Variable.getCPtr(arg2)), true);
	}
	
	public Node(long id, Rectangle arg1) {
		this(colaJNI.new_Node__SWIG_1(id, Rectangle.getCPtr(arg1), arg1), true);
	}
	
	public void setDesiredPos(double d, double weight) {
		colaJNI.Node_setDesiredPos__SWIG_0(swigCPtr, this, d, weight);
	}
	
	public void setDesiredPos(double d) {
		colaJNI.Node_setDesiredPos__SWIG_1(swigCPtr, this, d);
	}
	
	public double initialPos() {
		return colaJNI.Node_initialPos(swigCPtr, this);
	}
	
	public double finalPos() {
		return colaJNI.Node_finalPos(swigCPtr, this);
	}
	
	public double posOnLine(double alpha) {
		return colaJNI.Node_posOnLine(swigCPtr, this, alpha);
	}
	
	public SWIGTYPE_p_vpsc__Variable getVarOrig() {
		long cPtr = colaJNI.Node_getVarOrig(swigCPtr, this);
		return (cPtr == 0) ? null : new SWIGTYPE_p_vpsc__Variable(cPtr, false);
	}
	
	public void setVar(SWIGTYPE_p_vpsc__Variable value) {
		colaJNI.Node_var_set(swigCPtr, this, SWIGTYPE_p_vpsc__Variable.getCPtr(value));
	}
	
	public SWIGTYPE_p_vpsc__Variable getVar() {
		long cPtr = colaJNI.Node_var_get(swigCPtr, this);
		return (cPtr == 0) ? null : new SWIGTYPE_p_vpsc__Variable(cPtr, false);
	}
	
}
