/*
 * ----------------------------------------------------------------------------
 * This file was automatically generated by SWIG (http://www.swig.org).
 * Version 1.3.31
 * Do not make changes to this file unless you know what you are doing--modify
 * the SWIG interface file instead.
 * -----------------------------------------------------------------------------
 */

package colajava;

public class RootCluster extends Cluster {
	private long swigCPtr;
	
	protected RootCluster(long cPtr, boolean cMemoryOwn) {
		super(colaJNI.SWIGRootClusterUpcast(cPtr), cMemoryOwn);
		swigCPtr = cPtr;
	}
	
	protected static long getCPtr(RootCluster obj) {
		return (obj == null) ? 0 : obj.swigCPtr;
	}
	
	@Override
	protected void finalize() {
		delete();
	}
	
	@Override
	public synchronized void delete() {
		if (swigCPtr != 0 && swigCMemOwn) {
			swigCMemOwn = false;
			colaJNI.delete_RootCluster(swigCPtr);
		}
		swigCPtr = 0;
		super.delete();
	}
	
	@Override
	public void computeBoundary(RectPtrVector rs) {
		colaJNI.RootCluster_computeBoundary(swigCPtr, this, RectPtrVector.getCPtr(rs), rs);
	}
	
	public RootCluster() {
		this(colaJNI.new_RootCluster(), true);
	}
	
}
