/*
 * ----------------------------------------------------------------------------
 * This file was automatically generated by SWIG (http://www.swig.org).
 * Version 1.3.31
 * Do not make changes to this file unless you know what you are doing--modify
 * the SWIG interface file instead.
 * -----------------------------------------------------------------------------
 */

package colajava;

public class UnsatisfiableConstraintInfo {
	private long swigCPtr;
	protected boolean swigCMemOwn;
	
	protected UnsatisfiableConstraintInfo(long cPtr, boolean cMemoryOwn) {
		swigCMemOwn = cMemoryOwn;
		swigCPtr = cPtr;
	}
	
	protected static long getCPtr(UnsatisfiableConstraintInfo obj) {
		return (obj == null) ? 0 : obj.swigCPtr;
	}
	
	@Override
	protected void finalize() {
		delete();
	}
	
	public synchronized void delete() {
		if (swigCPtr != 0 && swigCMemOwn) {
			swigCMemOwn = false;
			colaJNI.delete_UnsatisfiableConstraintInfo(swigCPtr);
		}
		swigCPtr = 0;
	}
	
	public UnsatisfiableConstraintInfo(SWIGTYPE_p_vpsc__Constraint c) {
		this(colaJNI.new_UnsatisfiableConstraintInfo(SWIGTYPE_p_vpsc__Constraint.getCPtr(c)), true);
	}
	
	public void setVlid(long value) {
		colaJNI.UnsatisfiableConstraintInfo_vlid_set(swigCPtr, this, value);
	}
	
	public long getVlid() {
		return colaJNI.UnsatisfiableConstraintInfo_vlid_get(swigCPtr, this);
	}
	
	public void setVrid(long value) {
		colaJNI.UnsatisfiableConstraintInfo_vrid_set(swigCPtr, this, value);
	}
	
	public long getVrid() {
		return colaJNI.UnsatisfiableConstraintInfo_vrid_get(swigCPtr, this);
	}
	
	public void setGap(double value) {
		colaJNI.UnsatisfiableConstraintInfo_gap_set(swigCPtr, this, value);
	}
	
	public double getGap() {
		return colaJNI.UnsatisfiableConstraintInfo_gap_get(swigCPtr, this);
	}
	
}
