/*
 * ----------------------------------------------------------------------------
 * This file was automatically generated by SWIG (http://www.swig.org).
 * Version 1.3.31
 * Do not make changes to this file unless you know what you are doing--modify
 * the SWIG interface file instead.
 * -----------------------------------------------------------------------------
 */

package colajava;

public class AlignmentConstraintPairList {
	private long swigCPtr;
	protected boolean swigCMemOwn;
	
	protected AlignmentConstraintPairList(long cPtr, boolean cMemoryOwn) {
		swigCMemOwn = cMemoryOwn;
		swigCPtr = cPtr;
	}
	
	protected static long getCPtr(AlignmentConstraintPairList obj) {
		return (obj == null) ? 0 : obj.swigCPtr;
	}
	
	@Override
	protected void finalize() {
		delete();
	}
	
	public synchronized void delete() {
		if (swigCPtr != 0 && swigCMemOwn) {
			swigCMemOwn = false;
			colaJNI.delete_AlignmentConstraintPairList(swigCPtr);
		}
		swigCPtr = 0;
	}
	
	public AlignmentConstraintPairList() {
		this(colaJNI.new_AlignmentConstraintPairList__SWIG_0(), true);
	}
	
	public AlignmentConstraintPairList(long n) {
		this(colaJNI.new_AlignmentConstraintPairList__SWIG_1(n), true);
	}
	
	public long size() {
		return colaJNI.AlignmentConstraintPairList_size(swigCPtr, this);
	}
	
	public long capacity() {
		return colaJNI.AlignmentConstraintPairList_capacity(swigCPtr, this);
	}
	
	public void reserve(long n) {
		colaJNI.AlignmentConstraintPairList_reserve(swigCPtr, this, n);
	}
	
	public boolean isEmpty() {
		return colaJNI.AlignmentConstraintPairList_isEmpty(swigCPtr, this);
	}
	
	public void clear() {
		colaJNI.AlignmentConstraintPairList_clear(swigCPtr, this);
	}
	
	public void add(AlignmentConstraintPair x) {
		colaJNI.AlignmentConstraintPairList_add(swigCPtr, this, AlignmentConstraintPair.getCPtr(x), x);
	}
	
	public AlignmentConstraintPair get(int i) {
		return new AlignmentConstraintPair(colaJNI.AlignmentConstraintPairList_get(swigCPtr, this, i), false);
	}
	
	public void set(int i, AlignmentConstraintPair x) {
		colaJNI.AlignmentConstraintPairList_set(swigCPtr, this, i, AlignmentConstraintPair.getCPtr(x), x);
	}
	
}
