/*
 * ----------------------------------------------------------------------------
 * This file was automatically generated by SWIG (http://www.swig.org).
 * Version 1.3.31
 * Do not make changes to this file unless you know what you are doing--modify
 * the SWIG interface file instead.
 * -----------------------------------------------------------------------------
 */

package colajava;

public class Lock {
	private long swigCPtr;
	protected boolean swigCMemOwn;
	
	protected Lock(long cPtr, boolean cMemoryOwn) {
		swigCMemOwn = cMemoryOwn;
		swigCPtr = cPtr;
	}
	
	protected static long getCPtr(Lock obj) {
		return (obj == null) ? 0 : obj.swigCPtr;
	}
	
	@Override
	protected void finalize() {
		delete();
	}
	
	public synchronized void delete() {
		if (swigCPtr != 0 && swigCMemOwn) {
			swigCMemOwn = false;
			colaJNI.delete_Lock(swigCPtr);
		}
		swigCPtr = 0;
	}
	
	public Lock() {
		this(colaJNI.new_Lock__SWIG_0(), true);
	}
	
	public Lock(long id, double X, double Y) {
		this(colaJNI.new_Lock__SWIG_1(id, X, Y), true);
	}
	
	public long getID() {
		return colaJNI.Lock_getID(swigCPtr, this);
	}
	
	public double pos(Dim dim) {
		return colaJNI.Lock_pos(swigCPtr, this, dim.swigValue());
	}
	
}
