/*
 * ----------------------------------------------------------------------------
 * This file was automatically generated by SWIG (http://www.swig.org).
 * Version 1.3.31
 * Do not make changes to this file unless you know what you are doing--modify
 * the SWIG interface file instead.
 * -----------------------------------------------------------------------------
 */

package colajava;

public final class Dim {
	public final static Dim HORIZONTAL = new Dim("HORIZONTAL", colaJNI.HORIZONTAL_get());
	public final static Dim VERTICAL = new Dim("VERTICAL", colaJNI.VERTICAL_get());
	
	public final int swigValue() {
		return swigValue;
	}
	
	@Override
	public String toString() {
		return swigName;
	}
	
	public static Dim swigToEnum(int swigValue) {
		if (swigValue < swigValues.length && swigValue >= 0 && swigValues[swigValue].swigValue == swigValue)
			return swigValues[swigValue];
		for (int i = 0; i < swigValues.length; i++)
			if (swigValues[i].swigValue == swigValue)
				return swigValues[i];
		throw new IllegalArgumentException("No enum " + Dim.class + " with value " + swigValue);
	}
	
	private Dim(String swigName) {
		this.swigName = swigName;
		this.swigValue = swigNext++;
	}
	
	private Dim(String swigName, int swigValue) {
		this.swigName = swigName;
		this.swigValue = swigValue;
		swigNext = swigValue + 1;
	}
	
	private Dim(String swigName, Dim swigEnum) {
		this.swigName = swigName;
		this.swigValue = swigEnum.swigValue;
		swigNext = this.swigValue + 1;
	}
	
	private static Dim[] swigValues = { HORIZONTAL, VERTICAL };
	private static int swigNext = 0;
	private final int swigValue;
	private final String swigName;
}
