/*
 * ----------------------------------------------------------------------------
 * This file was automatically generated by SWIG (http://www.swig.org).
 * Version 1.3.31
 * Do not make changes to this file unless you know what you are doing--modify
 * the SWIG interface file instead.
 * -----------------------------------------------------------------------------
 */

package colajava;

public class PageBoundaryConstraints extends CompoundConstraint {
	private long swigCPtr;
	
	protected PageBoundaryConstraints(long cPtr, boolean cMemoryOwn) {
		super(colaJNI.SWIGPageBoundaryConstraintsUpcast(cPtr), cMemoryOwn);
		swigCPtr = cPtr;
	}
	
	protected static long getCPtr(PageBoundaryConstraints obj) {
		return (obj == null) ? 0 : obj.swigCPtr;
	}
	
	@Override
	protected void finalize() {
		delete();
	}
	
	@Override
	public synchronized void delete() {
		if (swigCPtr != 0 && swigCMemOwn) {
			swigCMemOwn = false;
			colaJNI.delete_PageBoundaryConstraints(swigCPtr);
		}
		swigCPtr = 0;
		super.delete();
	}
	
	public PageBoundaryConstraints(double lm, double rm, double w) {
		this(colaJNI.new_PageBoundaryConstraints__SWIG_0(lm, rm, w), true);
	}
	
	public PageBoundaryConstraints(double lm, double rm, double lw, double rw) {
		this(colaJNI.new_PageBoundaryConstraints__SWIG_1(lm, rm, lw, rw), true);
	}
	
	@Override
	public void generateVariables(SWIGTYPE_p_std__vectorTvpsc__Variable_p_t vars) {
		colaJNI.PageBoundaryConstraints_generateVariables(swigCPtr, this, SWIGTYPE_p_std__vectorTvpsc__Variable_p_t.getCPtr(vars));
	}
	
	@Override
	public void generateSeparationConstraints(SWIGTYPE_p_std__vectorTvpsc__Variable_p_t vars, SWIGTYPE_p_std__vectorTvpsc__Constraint_p_t gcs) {
		colaJNI.PageBoundaryConstraints_generateSeparationConstraints(swigCPtr, this, SWIGTYPE_p_std__vectorTvpsc__Variable_p_t.getCPtr(vars),
							SWIGTYPE_p_std__vectorTvpsc__Constraint_p_t.getCPtr(gcs));
	}
	
	@Override
	public void updatePosition() {
		colaJNI.PageBoundaryConstraints_updatePosition(swigCPtr, this);
	}
	
	public double getActualLeftMargin() {
		return colaJNI.PageBoundaryConstraints_getActualLeftMargin(swigCPtr, this);
	}
	
	public double getActualRightMargin() {
		return colaJNI.PageBoundaryConstraints_getActualRightMargin(swigCPtr, this);
	}
	
	public void setOffsets(OffsetList value) {
		colaJNI.PageBoundaryConstraints_offsets_set(swigCPtr, this, OffsetList.getCPtr(value), value);
	}
	
	public OffsetList getOffsets() {
		long cPtr = colaJNI.PageBoundaryConstraints_offsets_get(swigCPtr, this);
		return (cPtr == 0) ? null : new OffsetList(cPtr, false);
	}
	
}
