/*
 * ----------------------------------------------------------------------------
 * This file was automatically generated by SWIG (http://www.swig.org).
 * Version 1.3.31
 * Do not make changes to this file unless you know what you are doing--modify
 * the SWIG interface file instead.
 * -----------------------------------------------------------------------------
 */

package colajava;

public class Avoid_Edge {
	private long swigCPtr;
	protected boolean swigCMemOwn;
	
	protected Avoid_Edge(long cPtr, boolean cMemoryOwn) {
		swigCMemOwn = cMemoryOwn;
		swigCPtr = cPtr;
	}
	
	protected static long getCPtr(Avoid_Edge obj) {
		return (obj == null) ? 0 : obj.swigCPtr;
	}
	
	@Override
	protected void finalize() {
		delete();
	}
	
	public synchronized void delete() {
		if (swigCPtr != 0 && swigCMemOwn) {
			swigCMemOwn = false;
			colaJNI.delete_Avoid_Edge(swigCPtr);
		}
		swigCPtr = 0;
	}
	
	public void setA(Point value) {
		colaJNI.Avoid_Edge_a_set(swigCPtr, this, Point.getCPtr(value), value);
	}
	
	public Point getA() {
		long cPtr = colaJNI.Avoid_Edge_a_get(swigCPtr, this);
		return (cPtr == 0) ? null : new Point(cPtr, false);
	}
	
	public void setB(Point value) {
		colaJNI.Avoid_Edge_b_set(swigCPtr, this, Point.getCPtr(value), value);
	}
	
	public Point getB() {
		long cPtr = colaJNI.Avoid_Edge_b_get(swigCPtr, this);
		return (cPtr == 0) ? null : new Point(cPtr, false);
	}
	
	public Avoid_Edge() {
		this(colaJNI.new_Avoid_Edge(), true);
	}
	
}
