/*
 * ----------------------------------------------------------------------------
 * This file was automatically generated by SWIG (http://www.swig.org).
 * Version 1.3.31
 * Do not make changes to this file unless you know what you are doing--modify
 * the SWIG interface file instead.
 * -----------------------------------------------------------------------------
 */

package colajava;

public class ColaDesiredPositions {
	private long swigCPtr;
	protected boolean swigCMemOwn;
	
	protected ColaDesiredPositions(long cPtr, boolean cMemoryOwn) {
		swigCMemOwn = cMemoryOwn;
		swigCPtr = cPtr;
	}
	
	protected static long getCPtr(ColaDesiredPositions obj) {
		return (obj == null) ? 0 : obj.swigCPtr;
	}
	
	@Override
	protected void finalize() {
		delete();
	}
	
	public synchronized void delete() {
		if (swigCPtr != 0 && swigCMemOwn) {
			swigCMemOwn = false;
			colaJNI.delete_ColaDesiredPositions(swigCPtr);
		}
		swigCPtr = 0;
	}
	
	public ColaDesiredPositions() {
		this(colaJNI.new_ColaDesiredPositions__SWIG_0(), true);
	}
	
	public ColaDesiredPositions(long n) {
		this(colaJNI.new_ColaDesiredPositions__SWIG_1(n), true);
	}
	
	public long size() {
		return colaJNI.ColaDesiredPositions_size(swigCPtr, this);
	}
	
	public long capacity() {
		return colaJNI.ColaDesiredPositions_capacity(swigCPtr, this);
	}
	
	public void reserve(long n) {
		colaJNI.ColaDesiredPositions_reserve(swigCPtr, this, n);
	}
	
	public boolean isEmpty() {
		return colaJNI.ColaDesiredPositions_isEmpty(swigCPtr, this);
	}
	
	public void clear() {
		colaJNI.ColaDesiredPositions_clear(swigCPtr, this);
	}
	
	public void add(DesiredPosition x) {
		colaJNI.ColaDesiredPositions_add(swigCPtr, this, DesiredPosition.getCPtr(x), x);
	}
	
	public DesiredPosition get(int i) {
		return new DesiredPosition(colaJNI.ColaDesiredPositions_get(swigCPtr, this, i), false);
	}
	
	public void set(int i, DesiredPosition x) {
		colaJNI.ColaDesiredPositions_set(swigCPtr, this, i, DesiredPosition.getCPtr(x), x);
	}
	
}
