/*
 * ----------------------------------------------------------------------------
 * This file was automatically generated by SWIG (http://www.swig.org).
 * Version 1.3.31
 * Do not make changes to this file unless you know what you are doing--modify
 * the SWIG interface file instead.
 * -----------------------------------------------------------------------------
 */

package colajava;

public class ConnRef {
	private long swigCPtr;
	protected boolean swigCMemOwn;
	
	protected ConnRef(long cPtr, boolean cMemoryOwn) {
		swigCMemOwn = cMemoryOwn;
		swigCPtr = cPtr;
	}
	
	protected static long getCPtr(ConnRef obj) {
		return (obj == null) ? 0 : obj.swigCPtr;
	}
	
	@Override
	protected void finalize() {
		delete();
	}
	
	public synchronized void delete() {
		if (swigCPtr != 0 && swigCMemOwn) {
			swigCMemOwn = false;
			colaJNI.delete_ConnRef(swigCPtr);
		}
		swigCPtr = 0;
	}
	
	public ConnRef(SWIGTYPE_p_Router router, long id) {
		this(colaJNI.new_ConnRef__SWIG_0(SWIGTYPE_p_Router.getCPtr(router), id), true);
	}
	
	public ConnRef(SWIGTYPE_p_Router router, long id, SWIGTYPE_p_Point src, SWIGTYPE_p_Point dst) {
		this(colaJNI.new_ConnRef__SWIG_1(SWIGTYPE_p_Router.getCPtr(router), id, SWIGTYPE_p_Point.getCPtr(src), SWIGTYPE_p_Point.getCPtr(dst)), true);
	}
	
	public void setType(long type) {
		colaJNI.ConnRef_setType(swigCPtr, this, type);
	}
	
	public SWIGTYPE_p_PolyLine route() {
		return new SWIGTYPE_p_PolyLine(colaJNI.ConnRef_route(swigCPtr, this), false);
	}
	
	public void set_route(SWIGTYPE_p_PolyLine route) {
		colaJNI.ConnRef_set_route(swigCPtr, this, SWIGTYPE_p_PolyLine.getCPtr(route));
	}
	
	public SWIGTYPE_p_Polygon display_route() {
		return new SWIGTYPE_p_Polygon(colaJNI.ConnRef_display_route(swigCPtr, this), false);
	}
	
	public boolean needsReroute() {
		return colaJNI.ConnRef_needsReroute(swigCPtr, this);
	}
	
	public void freeRoute() {
		colaJNI.ConnRef_freeRoute(swigCPtr, this);
	}
	
	public void calcRouteDist() {
		colaJNI.ConnRef_calcRouteDist(swigCPtr, this);
	}
	
	public void updateEndPoint(long type, SWIGTYPE_p_Point point) {
		colaJNI.ConnRef_updateEndPoint__SWIG_0(swigCPtr, this, type, SWIGTYPE_p_Point.getCPtr(point));
	}
	
	public void updateEndPoint(long type, SWIGTYPE_p_ShapeRef shapeRef, double x_position, double y_position) {
		colaJNI.ConnRef_updateEndPoint__SWIG_1(swigCPtr, this, type, SWIGTYPE_p_ShapeRef.getCPtr(shapeRef), x_position, y_position);
	}
	
	public void updateEndPoint(long type, SWIGTYPE_p_ShapeRef shapeRef, double x_position) {
		colaJNI.ConnRef_updateEndPoint__SWIG_2(swigCPtr, this, type, SWIGTYPE_p_ShapeRef.getCPtr(shapeRef), x_position);
	}
	
	public void updateEndPoint(long type, SWIGTYPE_p_ShapeRef shapeRef) {
		colaJNI.ConnRef_updateEndPoint__SWIG_3(swigCPtr, this, type, SWIGTYPE_p_ShapeRef.getCPtr(shapeRef));
	}
	
	public boolean updateEndPoint(long type, SWIGTYPE_p_VertID pointID, SWIGTYPE_p_Point pointSuggestion) {
		return colaJNI.ConnRef_updateEndPoint__SWIG_4(swigCPtr, this, type, SWIGTYPE_p_VertID.getCPtr(pointID), SWIGTYPE_p_Point.getCPtr(pointSuggestion));
	}
	
	public boolean updateEndPoint(long type, SWIGTYPE_p_VertID pointID) {
		return colaJNI.ConnRef_updateEndPoint__SWIG_5(swigCPtr, this, type, SWIGTYPE_p_VertID.getCPtr(pointID));
	}
	
	public void setEndPointId(long type, long id) {
		colaJNI.ConnRef_setEndPointId(swigCPtr, this, type, id);
	}
	
	public long getSrcShapeId() {
		return colaJNI.ConnRef_getSrcShapeId(swigCPtr, this);
	}
	
	public long getDstShapeId() {
		return colaJNI.ConnRef_getDstShapeId(swigCPtr, this);
	}
	
	public void makeActive() {
		colaJNI.ConnRef_makeActive(swigCPtr, this);
	}
	
	public void makeInactive() {
		colaJNI.ConnRef_makeInactive(swigCPtr, this);
	}
	
	public void lateSetup(SWIGTYPE_p_Point src, SWIGTYPE_p_Point dst) {
		colaJNI.ConnRef_lateSetup(swigCPtr, this, SWIGTYPE_p_Point.getCPtr(src), SWIGTYPE_p_Point.getCPtr(dst));
	}
	
	public long id() {
		return colaJNI.ConnRef_id(swigCPtr, this);
	}
	
	public SWIGTYPE_p_VertInf src() {
		long cPtr = colaJNI.ConnRef_src(swigCPtr, this);
		return (cPtr == 0) ? null : new SWIGTYPE_p_VertInf(cPtr, false);
	}
	
	public SWIGTYPE_p_VertInf dst() {
		long cPtr = colaJNI.ConnRef_dst(swigCPtr, this);
		return (cPtr == 0) ? null : new SWIGTYPE_p_VertInf(cPtr, false);
	}
	
	public SWIGTYPE_p_VertInf start() {
		long cPtr = colaJNI.ConnRef_start(swigCPtr, this);
		return (cPtr == 0) ? null : new SWIGTYPE_p_VertInf(cPtr, false);
	}
	
	public void removeFromGraph() {
		colaJNI.ConnRef_removeFromGraph(swigCPtr, this);
	}
	
	public boolean isInitialised() {
		return colaJNI.ConnRef_isInitialised(swigCPtr, this);
	}
	
	public void unInitialise() {
		colaJNI.ConnRef_unInitialise(swigCPtr, this);
	}
	
	public void setCallback(SWIGTYPE_p_f_p_void__void cb, SWIGTYPE_p_void ptr) {
		colaJNI.ConnRef_setCallback(swigCPtr, this, SWIGTYPE_p_f_p_void__void.getCPtr(cb), SWIGTYPE_p_void.getCPtr(ptr));
	}
	
	public void handleInvalid() {
		colaJNI.ConnRef_handleInvalid(swigCPtr, this);
	}
	
	public int generatePath() {
		return colaJNI.ConnRef_generatePath__SWIG_0(swigCPtr, this);
	}
	
	public int generatePath(SWIGTYPE_p_Point p0, SWIGTYPE_p_Point p1) {
		return colaJNI.ConnRef_generatePath__SWIG_1(swigCPtr, this, SWIGTYPE_p_Point.getCPtr(p0), SWIGTYPE_p_Point.getCPtr(p1));
	}
	
	public void makePathInvalid() {
		colaJNI.ConnRef_makePathInvalid(swigCPtr, this);
	}
	
	public SWIGTYPE_p_Router router() {
		long cPtr = colaJNI.ConnRef_router(swigCPtr, this);
		return (cPtr == 0) ? null : new SWIGTYPE_p_Router(cPtr, false);
	}
	
	public void setHateCrossings(boolean value) {
		colaJNI.ConnRef_setHateCrossings(swigCPtr, this, value);
	}
	
	public boolean doesHateCrossings() {
		return colaJNI.ConnRef_doesHateCrossings(swigCPtr, this);
	}
	
}
