/*
 * ----------------------------------------------------------------------------
 * This file was automatically generated by SWIG (http://www.swig.org).
 * Version 1.3.31
 * Do not make changes to this file unless you know what you are doing--modify
 * the SWIG interface file instead.
 * -----------------------------------------------------------------------------
 */

package colajava;

public class DistributionConstraint extends CompoundConstraint {
	private long swigCPtr;
	
	protected DistributionConstraint(long cPtr, boolean cMemoryOwn) {
		super(colaJNI.SWIGDistributionConstraintUpcast(cPtr), cMemoryOwn);
		swigCPtr = cPtr;
	}
	
	protected static long getCPtr(DistributionConstraint obj) {
		return (obj == null) ? 0 : obj.swigCPtr;
	}
	
	@Override
	protected void finalize() {
		delete();
	}
	
	@Override
	public synchronized void delete() {
		if (swigCPtr != 0 && swigCMemOwn) {
			swigCMemOwn = false;
			colaJNI.delete_DistributionConstraint(swigCPtr);
		}
		swigCPtr = 0;
		super.delete();
	}
	
	public DistributionConstraint() {
		this(colaJNI.new_DistributionConstraint(), true);
	}
	
	@Override
	public void generateVariables(SWIGTYPE_p_std__vectorTvpsc__Variable_p_t vars) {
		colaJNI.DistributionConstraint_generateVariables(swigCPtr, this, SWIGTYPE_p_std__vectorTvpsc__Variable_p_t.getCPtr(vars));
	}
	
	@Override
	public void generateSeparationConstraints(SWIGTYPE_p_std__vectorTvpsc__Variable_p_t vars, SWIGTYPE_p_std__vectorTvpsc__Constraint_p_t gcs) {
		colaJNI.DistributionConstraint_generateSeparationConstraints(swigCPtr, this, SWIGTYPE_p_std__vectorTvpsc__Variable_p_t.getCPtr(vars),
							SWIGTYPE_p_std__vectorTvpsc__Constraint_p_t.getCPtr(gcs));
	}
	
	public void setSeparation(double sep) {
		colaJNI.DistributionConstraint_setSeparation(swigCPtr, this, sep);
	}
	
	public void setCs(SWIGTYPE_p_std__vectorTvpsc__Constraint_p_t value) {
		colaJNI.DistributionConstraint_cs_set(swigCPtr, this, SWIGTYPE_p_std__vectorTvpsc__Constraint_p_t.getCPtr(value));
	}
	
	public SWIGTYPE_p_std__vectorTvpsc__Constraint_p_t getCs() {
		long cPtr = colaJNI.DistributionConstraint_cs_get(swigCPtr, this);
		return (cPtr == 0) ? null : new SWIGTYPE_p_std__vectorTvpsc__Constraint_p_t(cPtr, false);
	}
	
	public void setAcs(AlignmentConstraintPairList value) {
		colaJNI.DistributionConstraint_acs_set(swigCPtr, this, AlignmentConstraintPairList.getCPtr(value), value);
	}
	
	public AlignmentConstraintPairList getAcs() {
		long cPtr = colaJNI.DistributionConstraint_acs_get(swigCPtr, this);
		return (cPtr == 0) ? null : new AlignmentConstraintPairList(cPtr, false);
	}
	
	public void setIndicator(SWIGTYPE_p_void value) {
		colaJNI.DistributionConstraint_indicator_set(swigCPtr, this, SWIGTYPE_p_void.getCPtr(value));
	}
	
	public SWIGTYPE_p_void getIndicator() {
		long cPtr = colaJNI.DistributionConstraint_indicator_get(swigCPtr, this);
		return (cPtr == 0) ? null : new SWIGTYPE_p_void(cPtr, false);
	}
	
	public void setSep(double value) {
		colaJNI.DistributionConstraint_sep_set(swigCPtr, this, value);
	}
	
	public double getSep() {
		return colaJNI.DistributionConstraint_sep_get(swigCPtr, this);
	}
	
}
