/*
 * ----------------------------------------------------------------------------
 * This file was automatically generated by SWIG (http://www.swig.org).
 * Version 1.3.31
 * Do not make changes to this file unless you know what you are doing--modify
 * the SWIG interface file instead.
 * -----------------------------------------------------------------------------
 */

package colajava;

public class OffsetPair {
	private long swigCPtr;
	protected boolean swigCMemOwn;
	
	protected OffsetPair(long cPtr, boolean cMemoryOwn) {
		swigCMemOwn = cMemoryOwn;
		swigCPtr = cPtr;
	}
	
	protected static long getCPtr(OffsetPair obj) {
		return (obj == null) ? 0 : obj.swigCPtr;
	}
	
	@Override
	protected void finalize() {
		delete();
	}
	
	public synchronized void delete() {
		if (swigCPtr != 0 && swigCMemOwn) {
			swigCMemOwn = false;
			colaJNI.delete_OffsetPair(swigCPtr);
		}
		swigCPtr = 0;
	}
	
	public OffsetPair() {
		this(colaJNI.new_OffsetPair__SWIG_0(), true);
	}
	
	public OffsetPair(long first, double second) {
		this(colaJNI.new_OffsetPair__SWIG_1(first, second), true);
	}
	
	public OffsetPair(OffsetPair p) {
		this(colaJNI.new_OffsetPair__SWIG_2(OffsetPair.getCPtr(p), p), true);
	}
	
	public void setFirst(long value) {
		colaJNI.OffsetPair_first_set(swigCPtr, this, value);
	}
	
	public long getFirst() {
		return colaJNI.OffsetPair_first_get(swigCPtr, this);
	}
	
	public void setSecond(double value) {
		colaJNI.OffsetPair_second_set(swigCPtr, this, value);
	}
	
	public double getSecond() {
		return colaJNI.OffsetPair_second_get(swigCPtr, this);
	}
	
}
