/*
 * ----------------------------------------------------------------------------
 * This file was automatically generated by SWIG (http://www.swig.org).
 * Version 1.3.31
 * Do not make changes to this file unless you know what you are doing--modify
 * the SWIG interface file instead.
 * -----------------------------------------------------------------------------
 */

package colajava;

public class OrthogonalEdgeConstraint extends CompoundConstraint {
	private long swigCPtr;
	
	protected OrthogonalEdgeConstraint(long cPtr, boolean cMemoryOwn) {
		super(colaJNI.SWIGOrthogonalEdgeConstraintUpcast(cPtr), cMemoryOwn);
		swigCPtr = cPtr;
	}
	
	protected static long getCPtr(OrthogonalEdgeConstraint obj) {
		return (obj == null) ? 0 : obj.swigCPtr;
	}
	
	@Override
	protected void finalize() {
		delete();
	}
	
	@Override
	public synchronized void delete() {
		if (swigCPtr != 0 && swigCMemOwn) {
			swigCMemOwn = false;
			colaJNI.delete_OrthogonalEdgeConstraint(swigCPtr);
		}
		swigCPtr = 0;
		super.delete();
	}
	
	public OrthogonalEdgeConstraint(long l, long r) {
		this(colaJNI.new_OrthogonalEdgeConstraint(l, r), true);
	}
	
	public void setLeft(long value) {
		colaJNI.OrthogonalEdgeConstraint_left_set(swigCPtr, this, value);
	}
	
	public long getLeft() {
		return colaJNI.OrthogonalEdgeConstraint_left_get(swigCPtr, this);
	}
	
	public void setRight(long value) {
		colaJNI.OrthogonalEdgeConstraint_right_set(swigCPtr, this, value);
	}
	
	public long getRight() {
		return colaJNI.OrthogonalEdgeConstraint_right_get(swigCPtr, this);
	}
	
	@Override
	public void generateVariables(SWIGTYPE_p_std__vectorTvpsc__Variable_p_t vars) {
		colaJNI.OrthogonalEdgeConstraint_generateVariables(swigCPtr, this, SWIGTYPE_p_std__vectorTvpsc__Variable_p_t.getCPtr(vars));
	}
	
	@Override
	public void generateSeparationConstraints(SWIGTYPE_p_std__vectorTvpsc__Variable_p_t vs, SWIGTYPE_p_std__vectorTvpsc__Constraint_p_t cs) {
		colaJNI.OrthogonalEdgeConstraint_generateSeparationConstraints(swigCPtr, this, SWIGTYPE_p_std__vectorTvpsc__Variable_p_t.getCPtr(vs),
							SWIGTYPE_p_std__vectorTvpsc__Constraint_p_t.getCPtr(cs));
	}
	
	public void generateTopologyConstraints(Dim k, RectPtrVector rs, SWIGTYPE_p_std__vectorTvpsc__Variable_p_t vars,
						SWIGTYPE_p_std__vectorTvpsc__Constraint_p_t cs) {
		colaJNI.OrthogonalEdgeConstraint_generateTopologyConstraints(swigCPtr, this, k.swigValue(), RectPtrVector.getCPtr(rs), rs,
							SWIGTYPE_p_std__vectorTvpsc__Variable_p_t.getCPtr(vars), SWIGTYPE_p_std__vectorTvpsc__Constraint_p_t.getCPtr(cs));
	}
	
	public void setVpscConstraint(SWIGTYPE_p_vpsc__Constraint value) {
		colaJNI.OrthogonalEdgeConstraint_vpscConstraint_set(swigCPtr, this, SWIGTYPE_p_vpsc__Constraint.getCPtr(value));
	}
	
	public SWIGTYPE_p_vpsc__Constraint getVpscConstraint() {
		long cPtr = colaJNI.OrthogonalEdgeConstraint_vpscConstraint_get(swigCPtr, this);
		return (cPtr == 0) ? null : new SWIGTYPE_p_vpsc__Constraint(cPtr, false);
	}
	
}
