/*
 * ----------------------------------------------------------------------------
 * This file was automatically generated by SWIG (http://www.swig.org).
 * Version 1.3.31
 * Do not make changes to this file unless you know what you are doing--modify
 * the SWIG interface file instead.
 * -----------------------------------------------------------------------------
 */

package colajava;

public class Resize {
	private long swigCPtr;
	protected boolean swigCMemOwn;
	
	protected Resize(long cPtr, boolean cMemoryOwn) {
		swigCMemOwn = cMemoryOwn;
		swigCPtr = cPtr;
	}
	
	protected static long getCPtr(Resize obj) {
		return (obj == null) ? 0 : obj.swigCPtr;
	}
	
	@Override
	protected void finalize() {
		delete();
	}
	
	public synchronized void delete() {
		if (swigCPtr != 0 && swigCMemOwn) {
			swigCMemOwn = false;
			colaJNI.delete_Resize(swigCPtr);
		}
		swigCPtr = 0;
	}
	
	public Resize(long id, double x, double y, double w, double h) {
		this(colaJNI.new_Resize(id, x, y, w, h), true);
	}
	
	public long getID() {
		return colaJNI.Resize_getID(swigCPtr, this);
	}
	
	public Rectangle getTarget() {
		long cPtr = colaJNI.Resize_getTarget(swigCPtr, this);
		return (cPtr == 0) ? null : new Rectangle(cPtr, false);
	}
	
}
