/*
 * ----------------------------------------------------------------------------
 * This file was automatically generated by SWIG (http://www.swig.org).
 * Version 1.3.31
 * Do not make changes to this file unless you know what you are doing--modify
 * the SWIG interface file instead.
 * -----------------------------------------------------------------------------
 */

package colajava;

public class SWIGTYPE_p_Point {
	private long swigCPtr;
	
	protected SWIGTYPE_p_Point(long cPtr, boolean futureUse) {
		swigCPtr = cPtr;
	}
	
	protected SWIGTYPE_p_Point() {
		swigCPtr = 0;
	}
	
	protected static long getCPtr(SWIGTYPE_p_Point obj) {
		return (obj == null) ? 0 : obj.swigCPtr;
	}
}
