/*
 * ----------------------------------------------------------------------------
 * This file was automatically generated by SWIG (http://www.swig.org).
 * Version 1.3.31
 * Do not make changes to this file unless you know what you are doing--modify
 * the SWIG interface file instead.
 * -----------------------------------------------------------------------------
 */

package colajava;

public class TopologyEdgePtrVector {
	private long swigCPtr;
	protected boolean swigCMemOwn;
	
	protected TopologyEdgePtrVector(long cPtr, boolean cMemoryOwn) {
		swigCMemOwn = cMemoryOwn;
		swigCPtr = cPtr;
	}
	
	protected static long getCPtr(TopologyEdgePtrVector obj) {
		return (obj == null) ? 0 : obj.swigCPtr;
	}
	
	@Override
	protected void finalize() {
		delete();
	}
	
	public synchronized void delete() {
		if (swigCPtr != 0 && swigCMemOwn) {
			swigCMemOwn = false;
			colaJNI.delete_TopologyEdgePtrVector(swigCPtr);
		}
		swigCPtr = 0;
	}
	
	public TopologyEdgePtrVector() {
		this(colaJNI.new_TopologyEdgePtrVector__SWIG_0(), true);
	}
	
	public TopologyEdgePtrVector(long n) {
		this(colaJNI.new_TopologyEdgePtrVector__SWIG_1(n), true);
	}
	
	public long size() {
		return colaJNI.TopologyEdgePtrVector_size(swigCPtr, this);
	}
	
	public long capacity() {
		return colaJNI.TopologyEdgePtrVector_capacity(swigCPtr, this);
	}
	
	public void reserve(long n) {
		colaJNI.TopologyEdgePtrVector_reserve(swigCPtr, this, n);
	}
	
	public boolean isEmpty() {
		return colaJNI.TopologyEdgePtrVector_isEmpty(swigCPtr, this);
	}
	
	public void clear() {
		colaJNI.TopologyEdgePtrVector_clear(swigCPtr, this);
	}
	
	public void add(Edge x) {
		colaJNI.TopologyEdgePtrVector_add(swigCPtr, this, Edge.getCPtr(x));
	}
	
	public Edge get(int i) {
		long cPtr = colaJNI.TopologyEdgePtrVector_get(swigCPtr, this, i);
		return (cPtr == 0) ? null : new Edge(cPtr, false);
	}
	
	public void set(int i, Edge x) {
		colaJNI.TopologyEdgePtrVector_set(swigCPtr, this, i, Edge.getCPtr(x));
	}
	
}
