/*
 * ----------------------------------------------------------------------------
 * This file was automatically generated by SWIG (http://www.swig.org).
 * Version 1.3.31
 * Do not make changes to this file unless you know what you are doing--modify
 * the SWIG interface file instead.
 * -----------------------------------------------------------------------------
 */

package colajava;

public class TopologyNodePtrVector {
	private long swigCPtr;
	protected boolean swigCMemOwn;
	
	protected TopologyNodePtrVector(long cPtr, boolean cMemoryOwn) {
		swigCMemOwn = cMemoryOwn;
		swigCPtr = cPtr;
	}
	
	protected static long getCPtr(TopologyNodePtrVector obj) {
		return (obj == null) ? 0 : obj.swigCPtr;
	}
	
	@Override
	protected void finalize() {
		delete();
	}
	
	public synchronized void delete() {
		if (swigCPtr != 0 && swigCMemOwn) {
			swigCMemOwn = false;
			colaJNI.delete_TopologyNodePtrVector(swigCPtr);
		}
		swigCPtr = 0;
	}
	
	public TopologyNodePtrVector() {
		this(colaJNI.new_TopologyNodePtrVector__SWIG_0(), true);
	}
	
	public TopologyNodePtrVector(long n) {
		this(colaJNI.new_TopologyNodePtrVector__SWIG_1(n), true);
	}
	
	public long size() {
		return colaJNI.TopologyNodePtrVector_size(swigCPtr, this);
	}
	
	public long capacity() {
		return colaJNI.TopologyNodePtrVector_capacity(swigCPtr, this);
	}
	
	public void reserve(long n) {
		colaJNI.TopologyNodePtrVector_reserve(swigCPtr, this, n);
	}
	
	public boolean isEmpty() {
		return colaJNI.TopologyNodePtrVector_isEmpty(swigCPtr, this);
	}
	
	public void clear() {
		colaJNI.TopologyNodePtrVector_clear(swigCPtr, this);
	}
	
	public void add(Node x) {
		colaJNI.TopologyNodePtrVector_add(swigCPtr, this, Node.getCPtr(x));
	}
	
	public Node get(int i) {
		long cPtr = colaJNI.TopologyNodePtrVector_get(swigCPtr, this, i);
		return (cPtr == 0) ? null : new Node(cPtr, false);
	}
	
	public void set(int i, Node x) {
		colaJNI.TopologyNodePtrVector_set(swigCPtr, this, i, Node.getCPtr(x));
	}
	
}
