/*
 * ----------------------------------------------------------------------------
 * This file was automatically generated by SWIG (http://www.swig.org).
 * Version 1.3.31
 * Do not make changes to this file unless you know what you are doing--modify
 * the SWIG interface file instead.
 * -----------------------------------------------------------------------------
 */

package colajava;

public class TestConvergence {
	private long swigCPtr;
	protected boolean swigCMemOwn;
	
	protected TestConvergence(long cPtr, boolean cMemoryOwn) {
		swigCMemOwn = cMemoryOwn;
		swigCPtr = cPtr;
	}
	
	protected static long getCPtr(TestConvergence obj) {
		return (obj == null) ? 0 : obj.swigCPtr;
	}
	
	@Override
	protected void finalize() {
		delete();
	}
	
	public synchronized void delete() {
		if (swigCPtr != 0 && swigCMemOwn) {
			swigCMemOwn = false;
			colaJNI.delete_TestConvergence(swigCPtr);
		}
		swigCPtr = 0;
	}
	
	public void setOld_stress(double value) {
		colaJNI.TestConvergence_old_stress_set(swigCPtr, this, value);
	}
	
	public double getOld_stress() {
		return colaJNI.TestConvergence_old_stress_get(swigCPtr, this);
	}
	
	public TestConvergence(double tol, long maxiterations) {
		this(colaJNI.new_TestConvergence__SWIG_0(tol, maxiterations), true);
	}
	
	public TestConvergence(double tol) {
		this(colaJNI.new_TestConvergence__SWIG_1(tol), true);
	}
	
	public TestConvergence() {
		this(colaJNI.new_TestConvergence__SWIG_2(), true);
	}
	
	public boolean testoperator(double new_stress, SWIGTYPE_p_std__valarrayTdouble_t X, SWIGTYPE_p_std__valarrayTdouble_t Y) {
		return colaJNI.TestConvergence_testoperator(swigCPtr, this, new_stress, SWIGTYPE_p_std__valarrayTdouble_t.getCPtr(X), SWIGTYPE_p_std__valarrayTdouble_t
							.getCPtr(Y));
	}
	
	public void reset() {
		colaJNI.TestConvergence_reset(swigCPtr, this);
	}
	
	public double getTolerance() {
		return colaJNI.TestConvergence_tolerance_get(swigCPtr, this);
	}
	
	public long getMaxiterations() {
		return colaJNI.TestConvergence_maxiterations_get(swigCPtr, this);
	}
	
	public void setIterations(long value) {
		colaJNI.TestConvergence_iterations_set(swigCPtr, this, value);
	}
	
	public long getIterations() {
		return colaJNI.TestConvergence_iterations_get(swigCPtr, this);
	}
	
}
